const AGENTS=[
  {id:"codex",name:"Codex",mark:"C",role:"PC・コード・Git"},{id:"gemini",name:"Gemini",mark:"G",role:"調査・Google・別解"},
  {id:"claude",name:"Claude",mark:"Cl",role:"第二万能施工・独立監査"},{id:"manus",name:"Manus",mark:"M",role:"第一Web・販売施工"},
  {id:"notebooklm",name:"NotebookLM",mark:"N",role:"資料参照・出典抽出（読取専用）"}
];
const LABELS={queued:"受付済み",QUEUED:"次に実行",planning:"判断中",waiting_approval:"承認待ち",running:"施工中",reviewing:"検査中",retrying:"再施工待ち",completed:"完了",failed:"失敗",cancelled:"中止"};
const initial=[{role:"zero",text:"AI5 HUBへようこそ。私、ゼロにだけ指示してください。Local APIが目的を整理し、必要な兄弟だけに振り分けます。",at:new Date().toISOString(),routed:[]}];
const load=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}};
const state={messages:load("ai5.messages",initial),taskIds:load("ai5.tasks",[]),reported:new Set(load("ai5.reported",[])),approvalNotified:new Set(load("ai5.approvalNotified",[])),lineSeen:new Set(load("ai5.lineSeen",[])),longDraft:load("ai5.longDraft",null),csrf:null,mode:"offline",activeTask:null,poll:null,agentStatus:{},command:null,target:"auto",replyTo:null,attachmentId:null,historyFilter:"all",chatLevel:"NORMAL",installPrompt:null,installing:false,pushSubscribed:false,projects:[],projectCounts:{}};
const $=selector=>document.querySelector(selector);const agentsEl=$("#agents"),messagesEl=$("#messages"),composer=$("#composer"),promptEl=$("#prompt"),jobStatus=$("#jobStatus"),progress=$("#taskProgress"),resultDetails=$("#resultDetails"),approval=$("#approvalArea");
function escapeHtml(value=""){return String(value).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"})[c])}
function messageBody(value=""){const text=String(value),safe=escapeHtml(text).replace(/\n/g,"<br>");return text.length>800?`<details class="long-message"><summary>長文指示 ${text.length.toLocaleString()}文字</summary><span>${safe}</span></details>`:safe}
function persist(){localStorage.setItem("ai5.messages",JSON.stringify(state.messages.slice(-200)));localStorage.setItem("ai5.tasks",JSON.stringify(state.taskIds.slice(-30)));localStorage.setItem("ai5.reported",JSON.stringify([...state.reported].slice(-30)));localStorage.setItem("ai5.approvalNotified",JSON.stringify([...state.approvalNotified].slice(-30)));localStorage.setItem("ai5.lineSeen",JSON.stringify([...state.lineSeen].slice(-300)))}
function agentName(id){return AGENTS.find(agent=>agent.id===id)?.name||id}
function renderMessages(){const visible=state.messages.filter(message=>state.historyFilter==='all'||message.role===state.historyFilter||message.target===state.historyFilter||(message.routed||[]).includes(state.historyFilter));messagesEl.innerHTML=visible.map(message=>{const user=message.role==="user",meta=commandMeta(message.role),display=user?'本人':message.role==='zero'?'Zero':meta.name,mark=user?'本人':message.role==='zero'?'0':meta.mark;const chips=(message.routed||[]).map(id=>`<span class="chip">${escapeHtml(agentName(id))}</span>`).join("");const time=new Date(message.at).toLocaleTimeString("ja-JP",{hour:"2-digit",minute:"2-digit"});return `<article class="message ${user?"user":escapeHtml(message.role||'zero')}" data-message="${escapeHtml(message.id||'')}" data-agent="${escapeHtml(message.role||'zero')}"><span class="avatar">${escapeHtml(mark)}</span><div><div class="meta agent-label">${escapeHtml(display)}</div><div class="bubble">${messageBody(message.text)}${chips?`<div class="routing">${chips}</div>`:""}</div><div class="meta">${time}${!user&&message.id?` <button class="reply-button" type="button">↩ 返信</button>`:''}</div></div></article>`}).join("");messagesEl.scrollTop=messagesEl.scrollHeight}
function renderAgents(status={}){agentsEl.innerHTML=AGENTS.map(agent=>{const info=status[agent.id]||{state:"offline",connection:"not_connected"};const connection=info.connection==="mock"?"Mock接続":info.connection==="not_connected"?"未接続":"接続済";return `<div class="agent"><span class="avatar">${agent.mark}</span><span><b>${agent.name}</b><small>${agent.role}・${connection}</small></span><i class="status ${escapeHtml(info.state)}" title="${connection}"></i></div>`}).join("")}
function renderApproval(task){if(task.status!=="waiting_approval"){approval.className="approval-empty";approval.textContent="現在、本人確認が必要な操作はありません。";return}const review=task.approval?.zero_review||{};const ok=review.verdict==="APPROVAL_OK";const list=items=>(items||[]).map(item=>`<li>${escapeHtml(item)}</li>`).join("");approval.className=`approval-card ${ok?"recommended":"not-recommended"}`;approval.innerHTML=`<strong>Zero判定：${ok?"承認OK ✅":"承認非推奨 ⚠️"}</strong><p>${escapeHtml(review.reason||task.approval?.summary||"")}</p><b>リスク</b><ul>${list(review.risks)}</ul><b>確認済み事項</b><ul>${list(review.checks)}</ul><p>推奨：${ok?"承認して続行":"拒否して安全条件を修正"}</p><div><button data-action="approve">承認して続行</button><button data-action="cancel" class="danger">拒否</button></div><small>Zeroの判定は本人承認の代わりではありません。</small>`}
function renderTask(task){if(!task){jobStatus.className="job-card idle";jobStatus.innerHTML="<span>現在</span><b>指示待ち</b><small>ゼロにメッセージを送ってください</small>";progress.innerHTML="";resultDetails.hidden=true;renderApproval({status:"none"});renderAgents(state.agentStatus);return}state.activeTask=task;const routed=[task.assignedPrimary,...(task.assignedSecondary||[])];const live=structuredClone(state.agentStatus);if(live[task.assignedPrimary])live[task.assignedPrimary].state=({planning:"thinking",waiting_approval:"waiting",running:"running",reviewing:"thinking",completed:"completed",failed:"error",cancelled:"ready"})[task.status]||"ready";renderAgents(live);jobStatus.className=`job-card ${task.status}`;jobStatus.innerHTML=`<span>${escapeHtml(LABELS[task.status]||task.status)}</span><b>${escapeHtml(task.objective)}</b><small>担当: ${routed.map(agentName).join("・")} / ${state.mode.toUpperCase()}</small>`;progress.innerHTML=(task.timeline||[]).map((item,index,array)=>`<div class="progress-row ${index===array.length-1?"current":"done"}"><i></i><span><b>${escapeHtml(LABELS[item.status]||item.status)}</b><small>${escapeHtml(item.label)}</small></span></div>`).join("");const result=task.result;if(result){const files=(result.filesChanged||[]).join("、")||"なし";const tests=(result.tests||[]).join("、")||"記録なし";resultDetails.hidden=false;resultDetails.innerHTML=`<details><summary>結果・技術詳細</summary><dl><dt>task_id</dt><dd>${escapeHtml(task.taskId)}</dd><dt>開始</dt><dd>${escapeHtml(task.bridge?.startedAt||task.createdAt||"")}</dd><dt>完了</dt><dd>${escapeHtml(task.bridge?.finishedAt||task.updatedAt||"")}</dd><dt>実施内容</dt><dd>${escapeHtml(result.summary||"")}</dd><dt>検査</dt><dd>${escapeHtml(tests)}</dd><dt>変更</dt><dd>${escapeHtml(files)}</dd><dt>commit</dt><dd>${escapeHtml(result.commitId||"なし")}</dd><dt>失敗理由</dt><dd>${escapeHtml(result.failureReason||"なし")}</dd><dt>再試行</dt><dd>${result.retryable?"可能":"不可"}</dd><dt>本人操作</dt><dd>${result.userActionRequired?"必要":"不要"}</dd></dl></details>`}else resultDetails.hidden=true;renderApproval(task)}
async function api(path,options={},allowCsrfRefresh=true){const headers={"Content-Type":"application/json",...(options.headers||{})};if(state.csrf&&options.method&&options.method!=="GET")headers["X-AI5-CSRF"]=state.csrf;const response=await fetch(path,{...options,headers,credentials:"same-origin"});const raw=await response.text();let value={};try{value=raw?JSON.parse(raw):{}}catch{const error=new Error(`invalid_json_response (HTTP ${response.status})`);error.status=response.status;throw error}if(!response.ok){if(allowCsrfRefresh&&response.status===403&&value.error==='csrf'&&options.method&&options.method!=="GET"){const healthResponse=await fetch('/api/health',{credentials:'same-origin',cache:'no-store'});const healthRaw=await healthResponse.text();let health={};try{health=healthRaw?JSON.parse(healthRaw):{}}catch{}if(healthResponse.ok&&health.csrfToken){state.csrf=health.csrfToken;return api(path,options,false)}}const error=new Error(value.error||`HTTP ${response.status}`);error.status=response.status;throw error}return value}
async function textHash(text){const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text));return[...new Uint8Array(digest)].map(value=>value.toString(16).padStart(2,'0')).join('')}
function splitLongText(text,size=12000){const chunks=[];for(let start=0;start<text.length;){let end=Math.min(start+size,text.length);if(end<text.length&&/^[\uD800-\uDBFF]$/.test(text[end-1]))end--;chunks.push(text.slice(start,end));start=end}return chunks}
function longProgress(done,total,label='長文指示を受付中'){const box=$('#longMessageProgress'),percent=Math.round(done/total*100);box.hidden=false;box.querySelector('span').textContent=label;box.querySelector('progress').value=percent;box.querySelector('b').textContent=`${percent}%`}
async function sendLongMessage(text,payload){const hash=await textHash(text),chunks=splitLongText(text);if(chunks.length>64||text.length>262144)throw new Error('長文は256KB以下にしてください');let draft=state.longDraft;if(!draft||draft.hash!==hash){draft={id:crypto.randomUUID().replace(/-/g,''),hash,text,payload};state.longDraft=draft;localStorage.setItem('ai5.longDraft',JSON.stringify(draft))}let status=await api('/api/message-drafts',{method:'POST',body:JSON.stringify({messageId:draft.id,totalChunks:chunks.length,totalLength:text.length,contentHash:hash})});const received=new Set(status.receivedChunks||[]);for(let index=0;index<chunks.length;index++){if(received.has(index)){longProgress(index+1,chunks.length);continue}let lastError;for(let attempt=0;attempt<3;attempt++){try{status=await api(`/api/message-drafts/${draft.id}/chunks/${index}`,{method:'POST',body:JSON.stringify({content:chunks[index],chunkHash:await textHash(chunks[index])})});lastError=null;break}catch(error){lastError=error;if(!navigator.onLine)break}}if(lastError){longProgress(status.receivedCount||index,chunks.length,`送信停止・保存済み ${status.receivedCount||index}/${chunks.length}`);throw lastError}longProgress(index+1,chunks.length)}const task=await api(`/api/message-drafts/${draft.id}/commit`,{method:'POST',body:JSON.stringify(payload)});state.longDraft=null;localStorage.removeItem('ai5.longDraft');longProgress(1,1,'受付完了');setTimeout(()=>{$('#longMessageProgress').hidden=true},1200);return task}
async function refreshTaskLists(){try{const data=await api('/api/tasks');const tasks=data.tasks||[];const terminal=['completed','failed','cancelled'];const card=t=>`<button data-task="${escapeHtml(t.taskId)}"><b>${escapeHtml(t.objective||t.title)}</b><small>${escapeHtml(t.queue_reason?`次に実行 ${t.queue_position||''}`:LABELS[t.status]||t.status)}・${escapeHtml(t.assignedPrimary||t.assigned_agent||'')}</small></button>`;const active=tasks.filter(t=>!terminal.includes(t.status)&&t.status!=='waiting_approval');const waiting=tasks.filter(t=>t.status==='waiting_approval');const history=tasks.filter(t=>terminal.includes(t.status));state.waitingTaskId=waiting[0]?.taskId||null;$('#activeTasks').innerHTML=active.map(card).join('')||'<span class="empty">実行中の作業はありません。</span>';$('#historyTasks').innerHTML=history.map(card).join('')||'<span class="empty">履歴はありません。</span>';$('#approvalBadge').hidden=!waiting.length;$('#approvalBadge').textContent=waiting.length}catch{}}
function showAuth(message=""){state.mode="locked";$("#authGate").hidden=false;$("#authError").textContent=message;$("#connectionDot").className="online-dot error";$("#connectionText").textContent="本人認証が必要"}
async function bootstrap(){try{await api("/api/session");$("#authGate").hidden=true;const health=await api("/api/health");state.csrf=health.csrfToken;state.mode=health.mock?"mock":"live";$("#connectionDot").className="online-dot ready";$("#connectionText").textContent=`PCオンライン・Codex ${state.mode.toUpperCase()}`;let banner=$('#updateBanner');if(health.deployment?.state!=='STABLE'){if(!banner){banner=document.createElement('div');banner.id='updateBanner';banner.className='update-banner';document.querySelector('.chat header').after(banner)}banner.innerHTML=`<b>AI5 HUB UPDATE IN PROGRESS</b> 現在 ${escapeHtml(health.deployment.stableVersion)} / 次 ${escapeHtml(health.deployment.candidateVersion||'検査中')}`}else banner?.remove();const status=await api("/api/status");state.agentStatus=status.agents;renderAgents(status.agents);const latest=(status.tasks||[]).find(task=>state.taskIds.includes(task.taskId))||status.tasks?.[0];if(latest){renderTask(latest);watch(latest.taskId)}else renderTask(null)}catch(error){if(error.status===401){showAuth();return}state.mode="offline";$("#connectionDot").className="online-dot error";$("#connectionText").textContent="PCオフライン";renderAgents();jobStatus.innerHTML=`<span>OFFLINE</span><b>PCが現在オフラインです</b><small>タスクは送信されていません。接続後に自動復元します。</small>`}}
function zeroMessage(text,routed=[]){state.messages.push({role:"zero",text,at:new Date().toISOString(),routed});persist();renderMessages()}
function notify(title,body){if(!state.pushSubscribed&&'Notification'in window&&Notification.permission==='granted')new Notification(title,{body,icon:'/icons/ai5-icon-192.png',tag:'ai5-hub'})}
function decodeVapid(value){const padding='='.repeat((4-value.length%4)%4),base64=(value+padding).replace(/-/g,'+').replace(/_/g,'/'),raw=atob(base64);return Uint8Array.from([...raw].map(char=>char.charCodeAt(0)))}
async function enableBackgroundPush(){if(!('serviceWorker'in navigator)||!('PushManager'in window))throw new Error('この端末はバックグラウンド通知に対応していません');const permission=await Notification.requestPermission();if(permission!=='granted')throw new Error('通知が許可されていません');const registration=await navigator.serviceWorker.ready,config=await api('/api/push/public-key');let subscription=await registration.pushManager.getSubscription();if(!subscription)subscription=await registration.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:decodeVapid(config.publicKey)});await api('/api/push/subscribe',{method:'POST',body:JSON.stringify(subscription.toJSON())});state.pushSubscribed=true}
function report(task){if(task.status==="waiting_approval"){state.approvalNotified.add(task.taskId);persist();return}if(state.reported.has(task.taskId))return;state.reported.add(task.taskId);if(task.status==="completed"){const files=(task.result?.filesChanged||task.result?.changes||[]).join("、")||"なし";const tests=(task.result?.tests||[]).join("、")||"記録なし";zeroMessage(`完了。\n${task.result?.summary||"Codex施工が完了しました。"}\n検査: ${tests}\n変更: ${files}\n残件: ${(task.result?.warnings||task.result?.risks||[]).join("、")||"なし"}`,[task.assignedPrimary,...(task.assignedSecondary||[])])}else if(task.status==="failed"){zeroMessage(`施工に失敗しました。\n原因: ${task.result?.failureReason||task.errorType||"不明"}\n${task.result?.summary||"詳細ログを確認してください。"}\n再試行: ${task.result?.retryable?"可能":"不可"} / 本人操作: ${task.result?.userActionRequired?"必要":"不要"}`)}else if(task.status==="cancelled")zeroMessage("タスクを中止しました。");persist()}
async function refreshTask(id){try{const task=await api(`/api/tasks/${id}`);renderTask(task);if(task.status==="waiting_approval")report(task);if(["completed","failed","cancelled"].includes(task.status)){clearInterval(state.poll);state.poll=null;report(task)}return task}catch(error){jobStatus.innerHTML=`<span>ERROR</span><b>状態取得失敗</b><small>${escapeHtml(error.message)}</small>`}}
function watch(id){if(state.poll)clearInterval(state.poll);refreshTask(id);state.poll=setInterval(()=>refreshTask(id),650)}
composer.addEventListener("submit",async event=>{event.preventDefault();const text=promptEl.value.trim();if(!text||state.mode==="offline")return;composer.classList.add("sending");const local={role:"user",target:state.target,text,at:new Date().toISOString(),routed:[]};state.messages.push(local);promptEl.value="";persist();renderMessages();try{const key=crypto.randomUUID(),payload={target:state.target,replyTo:state.replyTo?.id||null,attachmentId:state.attachmentId,source:"teppei",priority:"normal",conversationId:"local-default"};const task=text.length>4000?await sendLongMessage(text,payload):await api("/api/tasks",{method:"POST",headers:{"Idempotency-Key":key},body:JSON.stringify({...payload,message:text})});local.id=task.taskId+'-user';state.lineSeen.add(local.id);state.replyTo=null;state.attachmentId=null;$('#attachmentStatus').textContent='';if(!state.taskIds.includes(task.taskId))state.taskIds.push(task.taskId);const routed=[task.assignedPrimary,...(task.assignedSecondary||[])];const response=task.queue_reason?`受付しました。現在のWriterと競合するためQueueへ保存しました（次 ${task.queue_position}）。`:task.requiresApproval?`了解。Zeroが安全確認し、${routed.map(agentName).join("・")}への指示を承認待ちにしました。`:`了解。Zero Safety Layerを通して${routed.map(agentName).join("・")}へ投入しました。`;zeroMessage(response,routed);renderTask(task);watch(task.taskId);refreshCommandCenter()}catch(error){if(state.longDraft){promptEl.value=state.longDraft.text;zeroMessage(`長文指示の送信に失敗しました。保存済みChunkから再送できます: ${error.message}`)}else zeroMessage(`受付に失敗しました: ${error.message}`)}finally{composer.classList.remove("sending")}});
approval.addEventListener("click",async event=>{const action=event.target.dataset.action;if(!action||!state.activeTask)return;if(state.poll){clearInterval(state.poll);state.poll=null}try{const body=action==="approve"?JSON.stringify({approvalToken:state.activeTask.approvalToken}):"{}";const task=await api(`/api/tasks/${state.activeTask.taskId}/${action}`,{method:"POST",body});renderTask(task);watch(task.taskId)}catch(error){zeroMessage(`承認操作に失敗しました: ${error.message}`);watch(state.activeTask.taskId)}});
promptEl.addEventListener("input",()=>{promptEl.style.height="auto";promptEl.style.height=`${Math.min(promptEl.scrollHeight,140)}px`});$("#flowButton").addEventListener("click",()=>$("#activity").classList.add("open"));$("#closeFlow").addEventListener("click",()=>$("#activity").classList.remove("open"));
$("#loginButton").addEventListener("click",async()=>{try{await api("/api/session",{method:"POST",body:"{}"});await bootstrap()}catch(error){showAuth(error.message==="authentication_failed"?"Tailscaleで本人確認できませんでした。":"PCへ接続できません。")}});
$("#logoutButton").addEventListener("click",async()=>{try{await api("/api/logout",{method:"POST",body:"{}"})}catch{}showAuth("ログアウトしました。")});
$("#notifyButton").addEventListener("click",async()=>{try{await enableBackgroundPush();zeroMessage('バックグラウンド通知を有効にしました。完了・承認待ち・重大失敗だけ通知します。')}catch(error){zeroMessage(`通知設定失敗: ${error.message}`)}});
window.addEventListener('beforeinstallprompt',event=>{event.preventDefault();state.installPrompt=event;$('#installButton').hidden=false});
async function pwaDiagnostics(){const chrome=/Chrome\//.test(navigator.userAgent)&&!/; wv\)/.test(navigator.userAgent);const standalone=matchMedia('(display-mode: standalone)').matches;let registration=null;let manifest='NG';let installed='取得不可';try{registration=await navigator.serviceWorker?.getRegistration('/');const response=await fetch('/manifest.webmanifest',{cache:'no-store'});manifest=response.ok?'OK':`NG (${response.status})`;if(navigator.getInstalledRelatedApps){const apps=await navigator.getInstalledRelatedApps();installed=apps.some(app=>app.platform==='webapp')?'WebAPK登録あり':'WebAPK登録なし'}}catch{}return `PWA診断 v35\nHTTPS: ${isSecureContext?'OK':'NG'}\nChrome本体: ${chrome?'OK':'NG（Gmail等の内蔵ブラウザでは不可）'}\nmanifest: ${manifest}\nService Worker: ${registration?.active?'OK':registration?'準備中':'NG'}\nChrome WebAPK: ${installed}\nアプリ表示: ${standalone?'standalone':'ブラウザ'}\nインストール候補: ${state.installPrompt?'OK':'NG'}`}
$('#diagnoseButton').addEventListener('click',async()=>zeroMessage(await pwaDiagnostics()));
$('#installButton').addEventListener('click',async()=>{if(state.installing)return;if(!state.installPrompt){zeroMessage(await pwaDiagnostics());return}state.installing=true;$('#installButton').disabled=true;try{state.installPrompt.prompt();const choice=await state.installPrompt.userChoice;state.installPrompt=null;$('#installButton').hidden=true;zeroMessage(choice.outcome==='accepted'?'Chromeがインストール要求を受け付けました。Android OSへの登録完了を確認してください。':'インストールを中止しました。')}finally{state.installing=false;$('#installButton').disabled=false}});
window.addEventListener('appinstalled',()=>{state.installPrompt=null;$('#installButton').hidden=true;zeroMessage('Chromeがインストール要求を受け付けました。Androidのホーム画面と設定→アプリへの登録確認が必要です。')});
const fmtJst=value=>value?new Intl.DateTimeFormat('ja-JP',{timeZone:'Asia/Tokyo',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}).format(new Date(value)):'—';
const stoppedFor=value=>{if(!value)return'—';const mins=Math.max(0,Math.floor((Date.now()-new Date(value))/60000));return mins<60?`${mins}分`:`${Math.floor(mins/60)}h ${mins%60}m`};
const priority=p=>p.stopCode==='ERROR_LOOP_STOP'||p.status==='FAILED'?0:p.blockedBy==='TEPPEI'?1:['ALL_AI_DONE_BUT_IDLE','NEXT_STEP_MISSING'].includes(p.stopCode)?2:p.blockedBy==='CODEX'?3:p.blockedBy==='ZERO'?4:p.status==='RUNNING'?6:p.phase==='RELEASE_READY'?7:['PUBLISHED','OPERATING'].includes(p.phase)?8:p.phase==='ARCHIVED'?10:5;
function projectVisible(p){const q=$('#projectSearch').value.trim().toLowerCase(),f=$('#projectFilter').value;if(q&&!`${p.name} ${p.repository?.name||''}`.toLowerCase().includes(q))return false;if(f==='all')return true;if(f==='autoOn')return p.autoExecution.enabled;if(f==='autoOff')return!p.autoExecution.enabled;if(f==='error')return p.status==='FAILED'||['ERROR_LOOP_STOP','CREDIT_PROTECTION_STOP'].includes(p.stopCode);if(f==='running')return p.status==='RUNNING';if(f==='selling')return['PUBLISHED','OPERATING'].includes(p.phase);return p.blockedBy===f||p.phase===f}
function renderProjects(){const c=state.projectCounts;$('#projectStats').innerHTML=[['🟢','進行中',c.running],['🔵','AI施工中',c.aiRunning],['🟠','停止',c.stopped],['🟣','本人待ち',c.human],['🔴','異常',c.error],['🟡','販売準備',c.release],['💰','販売中',c.selling],['✅','完了',c.completed]].map(x=>`<div><span>${x[0]} ${x[1]}</span><b>${x[2]||0}</b></div>`).join('')+`<div class="auto-total"><span>AUTO ACTIVE ${c.autoOn||0}</span><b>OFF ${c.autoOff||0}</b></div>`;const list=state.projects.filter(projectVisible).sort((a,b)=>priority(a)-priority(b));$('#projectList').innerHTML=list.map(p=>`<article class="project-card mode-${escapeHtml(p.autoExecution.mode||'OFF')}" data-project="${escapeHtml(p.projectId)}"><button class="project-open"><small>${escapeHtml(p.phase)}</small><h3>${escapeHtml(p.name)}</h3><strong class="stop-${escapeHtml(p.stopCode)}">${p.stopCode==='ALL_AI_DONE_BUT_IDLE'?'🟠 次工程未投入':escapeHtml(p.blockedBy==='NONE'?p.status:`${p.blockedBy} WAITING`)}</strong><dl><dt>停止</dt><dd>${fmtJst(p.timestamps.stoppedAt)}</dd><dt>停止時間</dt><dd>${stoppedFor(p.timestamps.stoppedAt)}</dd><dt>次</dt><dd>${escapeHtml(p.nextAction||'未設定')}</dd><dt>Codex / Zero</dt><dd>${escapeHtml(p.aiState.codex)} / ${escapeHtml(p.aiState.zero)}</dd><dt>GitHub</dt><dd>${escapeHtml(p.repository.sync?.state||'UNKNOWN')} ${escapeHtml((p.repository.latestCommit||'UNLINKED').slice(0,8))}</dd></dl></button><label class="auto-switch">AUTO EXECUTION <select data-auto="${escapeHtml(p.projectId)}"><option ${p.autoExecution.mode==='OFF'?'selected':''}>OFF</option><option value="DRY_RUN" ${p.autoExecution.mode==='DRY_RUN'?'selected':''}>DRY RUN</option><option value="LIVE" ${p.autoExecution.mode==='LIVE'?'selected':''}>LIVE</option></select></label></article>`).join('')||'<p class="project-empty">該当Projectはありません。</p>'}
async function refreshProjects(){try{const data=await api('/api/projects');state.projects=data.projects||[];state.projectCounts=data.counts||{};renderProjects()}catch(error){$('#projectList').innerHTML=`<p class="project-empty">状態取得失敗: ${escapeHtml(error.message)}</p>`}}
const COMMAND_AGENTS=[{id:'zero',name:'ZERO',mark:'0'},{id:'codex',name:'CODEX',mark:'C'},{id:'claude',name:'CLAUDE',mark:'Cl'},{id:'gemini',name:'GEMINI',mark:'G'},{id:'manus',name:'MANUS',mark:'M'},{id:'notebooklm',name:'NotebookLM',mark:'N'}];
const commandMeta=id=>COMMAND_AGENTS.find(x=>x.id===id)||{id,name:id,mark:'?'};
function commandCard(agent){const m=commandMeta(agent.id),elapsed=agent.startedAt?Math.max(0,Math.floor((Date.now()-new Date(agent.startedAt))/60000)):null;return `<button class="ai5-card" data-agent="${escapeHtml(agent.id)}"><div class="agent-top"><span class="avatar">${escapeHtml(m.mark)}</span><b>${escapeHtml(m.name)}</b><em class="agent-state ${escapeHtml(agent.state)}">● ${escapeHtml(agent.state)}</em></div><small>${escapeHtml(agent.role)}・${escapeHtml(agent.connection||'not_connected')}</small><span class="now">現在：${escapeHtml(agent.task||agent.stage||'待機')}</span><span>${agent.project?`Project：${escapeHtml(agent.project)}`:'Project：—'}${elapsed===null?'':`・${elapsed}分`}</span></button>`}
function taskMini(t){return `<button data-task="${escapeHtml(t.taskId)}"><b>${escapeHtml(t.objective||t.title)}</b><small>${escapeHtml(LABELS[t.status]||t.status)}・${escapeHtml(t.requested_target||t.assignedPrimary||'auto')}</small></button>`}
function renderCommandCenter(data){state.command=data;const siblings=['zero','codex','claude','gemini','manus'].map(id=>data.agents[id]);$('#commandHealth').innerHTML=[`PC ● ${data.pc}`,`Bridge ● ${data.bridge}`,`Tailscale ● ${data.tailscale}`,`承認待ち ${data.approvalCount}`].map(x=>`<span>${escapeHtml(x)}</span>`).join('');$('#ai5SiblingCards').innerHTML=siblings.map(commandCard).join('');$('#knowledgeCard').innerHTML=commandCard(data.agents.notebooklm);$('#liveAi5').innerHTML=Object.values(data.agents).map(a=>`<div class="live-row"><b>${escapeHtml(commandMeta(a.id).name)}　<span class="agent-state ${escapeHtml(a.state)}">● ${escapeHtml(a.state)}</span></b><span>${escapeHtml(a.task||a.stage||'待機')}</span></div>`).join('');$('#aiFlows').innerHTML=(data.flows||[]).map(f=>`<div class="flow-row">${(f.nodes||[]).map((n,i)=>`${i?'<i>→</i>':''}<b>${escapeHtml(commandMeta(n).name)}</b>`).join('')}<span>${escapeHtml(f.objective)}</span></div>`).join('')||'<div class="flow-row">現在のAI間通信はありません。</div>';$('#writeLocks').innerHTML=(data.writeLocks||[]).map(l=>`<div class="lock-row"><b>${escapeHtml(l.projectId||l.repository||'Project')}</b> Writer：Codex / Reviewer：Claude</div>`).join('')||'<div class="lock-row">現在のWRITE LOCKはありません。</div>';const waiting=(data.liveTasks||[]).filter(t=>t.status==='waiting_approval');$('#commandApprovals').innerHTML=waiting.map(taskMini).join('')||'<span class="empty">承認待ちはありません。</span>';$('#recentResults').innerHTML=(data.recentResults||[]).map(taskMini).join('')||'<span class="empty">結果はありません。</span>'}
async function refreshCommandCenter(){try{renderCommandCenter(await api('/api/command-center'))}catch(error){$('#commandHealth').innerHTML=`<span>取得失敗 ${escapeHtml(error.message)}</span>`}}
function selectTarget(target){state.target=target;$('#targetSelect').value=target;const name=target==='auto'?'ゼロ':agentName(target);promptEl.placeholder=target==='auto'?'ゼロに指示を入力…':`${name}に指示を入力…`;promptEl.setAttribute('aria-label',`${name}への指示`)}
$('#targetSelect').addEventListener('change',event=>selectTarget(event.target.value));
$('#chatFilters').addEventListener('click',event=>{const value=event.target.dataset.chatFilter;if(!value)return;state.historyFilter=value;$('#chatFilters').querySelectorAll('button').forEach(button=>button.classList.toggle('active',button===event.target));renderMessages()});
$('#ai5View').addEventListener('click',event=>{const taskId=event.target.closest('[data-task]')?.dataset.task;if(taskId){refreshTask(taskId);watch(taskId);$('#activity').classList.add('mobile-open');return}const id=event.target.closest('[data-agent]')?.dataset.agent;if(!id||!state.command)return;const a=state.command.agents[id],m=commandMeta(id);$('#agentDetail').innerHTML=`<small>AI5 COMMAND CENTER</small><h2>${escapeHtml(m.name)}</h2><div class="detail-badges"><b>${escapeHtml(a.state)}</b><b>${escapeHtml(a.connection)}</b></div><dl class="project-detail-grid"><dt>役割</dt><dd>${escapeHtml(a.role)}</dd><dt>Project</dt><dd>${escapeHtml(a.project||'—')}</dd><dt>Task</dt><dd>${escapeHtml(a.task||'待機')}</dd><dt>開始</dt><dd>${fmtJst(a.startedAt)}</dd><dt>現在工程</dt><dd>${escapeHtml(a.stage||'待機')}</dd><dt>直近結果</dt><dd>${escapeHtml(a.lastResult||'—')}</dd><dt>エラー</dt><dd>${escapeHtml(a.error?(a.historicalError?`過去障害：${a.error}`:a.error):'なし')}</dd><dt>制限</dt><dd>${escapeHtml(a.quota||'不明')}</dd></dl><button type="button" class="project-primary" data-direct="${escapeHtml(id)}">${escapeHtml(m.name)}へ指示</button>`;$('#agentDialog').showModal()});
$('#agentDetail').addEventListener('click',event=>{const id=event.target.dataset.direct;if(!id)return;$('#agentDialog').close();selectTarget(id==='zero'?'auto':id);document.querySelector('[data-view="zero"]').click();promptEl.focus()});
function openProject(p){const history=(p.history||[]).slice().reverse().map(h=>`<li><time>${fmtJst(h.at)}</time><b>${escapeHtml(h.actor||'SYSTEM')} ${escapeHtml(h.type)}</b><span>${escapeHtml(h.detail||'')}</span></li>`).join(''),g=p.githubResultLoop||{},l=p.autonomousLoop||{};$('#projectDetail').innerHTML=`<small>PROJECT CONTROL</small><h2>${escapeHtml(p.name)}</h2><div class="detail-badges"><b>${escapeHtml(p.phase)}</b><b>${escapeHtml(p.status)}</b><b>${escapeHtml(p.blockedBy)}</b></div><dl class="project-detail-grid"><dt>停止理由</dt><dd>${escapeHtml(p.stopReason||p.stopCode)}</dd><dt>停止日時</dt><dd>${fmtJst(p.timestamps.stoppedAt)}</dd><dt>再開日時</dt><dd>${fmtJst(p.timestamps.resumedAt)}</dd><dt>作業開始</dt><dd>${fmtJst(p.timestamps.workStartedAt)}</dd><dt>作業完了</dt><dd>${fmtJst(p.timestamps.workCompletedAt)}</dd><dt>Repository</dt><dd>${escapeHtml(p.repository.owner?`${p.repository.owner}/${p.repository.name}`:p.repository.name||'UNLINKED')}</dd><dt>branch / commit</dt><dd>${escapeHtml(p.repository.activeBranch||'—')} / ${escapeHtml((p.repository.latestCommit||'—').slice(0,8))}</dd><dt>品質</dt><dd>tests ${escapeHtml(p.qualityGate.tests)} / review ${escapeHtml(p.qualityGate.review)} / field ${escapeHtml(p.qualityGate.fieldValidation)}</dd><dt>GitHub Loop</dt><dd>${escapeHtml(g.currentTask||'待機')} / ${escapeHtml(g.assignedAI||'—')} / queue ${g.queue||0} / approval ${g.approval||0}</dd><dt>Autonomous Loop</dt><dd>${escapeHtml(l.lastDecision||'NONE')} / attempt ${l.attemptCount||0} / same ${l.sameFailureCount||0} / redispatch ${l.redispatchCount||0}</dd><dt>次の一手</dt><dd>${escapeHtml(g.nextAction||p.nextAction||'未設定')}</dd><dt>Cost / retry</dt><dd>${escapeHtml(p.executionPolicy.costClass)} / ${p.executionPolicy.retryCount||0} of ${p.executionPolicy.maxRetry}</dd></dl><h3>AI STATE</h3><div class="ai-state">${Object.entries(p.aiState).map(([k,v])=>`<span>${escapeHtml(k)}<b>${escapeHtml(v)}</b></span>`).join('')}</div><h3>TIMELINE</h3><ol class="project-timeline">${history||'<li>履歴なし</li>'}</ol>`;$('#projectDialog').showModal()}
$('#projectList').addEventListener('change',async event=>{const auto=event.target.closest('[data-auto]');if(!auto)return;event.stopPropagation();try{await api(`/api/projects/${auto.dataset.auto}/auto-execution`,{method:'POST',body:JSON.stringify({mode:auto.value})});await refreshProjects()}catch(error){zeroMessage(`AUTO切替失敗: ${error.message}`);await refreshProjects()}});$('#projectList').addEventListener('click',async event=>{if(event.target.closest('[data-auto]'))return;const id=event.target.closest('[data-project]')?.dataset.project;if(id){const p=await api(`/api/projects/${id}`);openProject(p)}});
$('#projectSearch').addEventListener('input',renderProjects);$('#projectFilter').addEventListener('change',renderProjects);$('#addProjectButton').addEventListener('click',()=>$('#projectCreateDialog').showModal());$('[data-close-project]').addEventListener('click',()=>$('#projectCreateDialog').close());$('#projectCreateForm').addEventListener('submit',async event=>{event.preventDefault();const body=Object.fromEntries(new FormData(event.target));try{await api('/api/projects',{method:'POST',body:JSON.stringify(body)});event.target.reset();$('#projectCreateDialog').close();await refreshProjects()}catch(error){zeroMessage(`Project登録失敗: ${error.message}`)}});
async function refreshSystem(){try{const [s,c]=await Promise.all([api('/api/projects/system'),api('/api/command-center')]),aiHealth=Object.fromEntries(Object.entries(c.agents).map(([id,a])=>[`AI5 ${commandMeta(id).name}`,`${a.state} / ${a.connection}`])),g=s.githubBus||{};$('#systemStatus').innerHTML=Object.entries({Scheduler:s.scheduler.status,'Last Scan':fmtJst(s.scheduler.lastScan),'Next Scan':fmtJst(s.scheduler.nextScan),Bridge:s.bridge.available?'READY':'STOPPED','GitHub Sync':state.projects.map(p=>p.repository.sync?.state||'UNKNOWN').join(' / '),'GitHub Result Loop':`${g.mode||'UNAVAILABLE'} / ${g.browser||'UNKNOWN'}`,'Zero Inbox unread':g.unread||0,'Result Bus':g.results||0,'Task Bus':g.tasks||0,'Remote Bus':g.remoteEnabled?'PRIVATE READY':'LOCAL SAFE','Active Project Lock':s.locks.length,'Codex Queue':s.queue,'AUTO LIVE':s.autoLive,'DRY RUN':s.dryRun,'Credit Stops':s.creditStops,'Approval Stops':s.approvalStops,...aiHealth}).map(([k,v])=>`<div><span>${escapeHtml(k)}</span><b>${escapeHtml(v)}</b></div>`).join('')}catch(error){$('#systemStatus').textContent=`SYSTEM取得失敗: ${error.message}`}}$('#scanProjectsButton').addEventListener('click',async()=>{try{await api('/api/projects/scan',{method:'POST',body:JSON.stringify({fetch:true,dryRun:false})});await refreshProjects();await refreshSystem()}catch(error){zeroMessage(`巡回失敗: ${error.message}`)}});
$('#longMessageTestButton').addEventListener('click',async()=>{if(state.mode==='offline')return;const text='スマホ長文受付の安全な実機テストです。PCやRepositoryを変更せず、LONG_MESSAGE_MOBILE_OKと検査結果だけ返してください。\n'+('完全性確認用文章。'.repeat(700));composer.classList.add('sending');try{const task=await sendLongMessage(text,{target:'codex',source:'mobile-long-diagnostic',priority:'normal',conversationId:'local-default'});if(!state.taskIds.includes(task.taskId))state.taskIds.push(task.taskId);zeroMessage(`長文受付PASS：${task.original_message_length}文字をTask 1件として受付しました。`,[task.assignedPrimary]);document.querySelector('[data-view="zero"]').click();renderTask(task);watch(task.taskId)}catch(error){zeroMessage(`長文受付テスト失敗：${error.message}`)}finally{composer.classList.remove('sending')}});
document.querySelectorAll('.bottom-nav button').forEach(button=>button.addEventListener('click',async()=>{document.querySelectorAll('.bottom-nav button').forEach(item=>item.classList.toggle('active',item===button));const view=button.dataset.view,projects=view==='projects',system=view==='system',ai5=view==='ai5';$('#projectsView').hidden=!projects;$('#systemView').hidden=!system;$('#ai5View').hidden=!ai5;$('#chatFilters').hidden=view!=='zero';messagesEl.hidden=projects||system||ai5;composer.hidden=projects||system||ai5;$('#activity').classList.remove('mobile-open');if(view==='zero')return;if(ai5){await refreshCommandCenter();return}if(projects){await refreshProjects();return}if(system){await refreshProjects();await refreshSystem()}}));
$('#taskLists').addEventListener('click',event=>{const id=event.target.closest('[data-task]')?.dataset.task;if(id){refreshTask(id);watch(id)}});
window.addEventListener("offline",()=>{$("#connectionDot").className="online-dot error";$("#connectionText").textContent="通信切断・施工はPCで継続中"});
window.addEventListener("online",()=>bootstrap());
if("serviceWorker" in navigator)navigator.serviceWorker.register("/service-worker.js?v=45",{scope:"/"}).then(async registration=>{state.pushSubscribed=!!(await registration.pushManager?.getSubscription())}).catch(error=>{console.error('AI5 HUB service worker registration failed',error);zeroMessage(`PWA初期化に失敗しました: ${error.message}`)});
async function refreshLineChat(){try{const data=await api('/api/chat',{headers:{'X-AI5-Chat-Level':state.chatLevel}});let changed=false;for(const item of data.messages||[]){if(state.lineSeen.has(item.id))continue;const local=item.agent==='user'?[...state.messages].reverse().find(message=>message.role==='user'&&!message.id&&message.text===item.text):null;if(local)local.id=item.id;else state.messages.push({id:item.id,role:item.agent||'zero',text:item.text,at:item.at,routed:[]});state.lineSeen.add(item.id);changed=true}if(changed){persist();renderMessages()}}catch{}}
$('#chatLevel').addEventListener('change',event=>{state.chatLevel=event.target.value;state.lineSeen.clear();state.messages=state.messages.filter(message=>!message.id);refreshLineChat()});
$('#attachmentInput').addEventListener('change',async event=>{const file=event.target.files?.[0];if(!file)return;if(file.size>5*1024*1024){zeroMessage('画像は5MB以下にしてください。');event.target.value='';return}try{const base64=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=reject;reader.readAsDataURL(file)}),saved=await api('/api/attachments',{method:'POST',body:JSON.stringify({mime:file.type,base64})});state.attachmentId=saved.id;$('#attachmentStatus').textContent=`画像 ${Math.ceil(saved.size/1024)}KB 添付済み`}catch(error){zeroMessage(`画像添付失敗: ${error.message}`)}finally{event.target.value=''}});
messagesEl.addEventListener('click',event=>{if(!event.target.closest('.reply-button'))return;const article=event.target.closest('[data-message]'),message=state.messages.find(item=>item.id===article.dataset.message);if(!message)return;state.replyTo={id:message.id,agent:article.dataset.agent};if(state.replyTo.agent&&!['zero','user'].includes(state.replyTo.agent))selectTarget(state.replyTo.agent);promptEl.placeholder=`${agentName(state.replyTo.agent)}への返信を入力…`;promptEl.focus()});
setInterval(()=>{refreshTaskLists();refreshLineChat();if(!$('#ai5View').hidden)refreshCommandCenter()},3000);
selectTarget('auto');renderMessages();renderAgents();bootstrap();refreshTaskLists();refreshLineChat();
