const AGENTS=[
  {id:"codex",name:"Codex",mark:"C",role:"PC・コード・Git"},{id:"gemini",name:"Gemini",mark:"G",role:"調査・Google・別解"},
  {id:"claude",name:"Claude",mark:"Cl",role:"第二万能施工・独立監査"},{id:"manus",name:"Manus",mark:"M",role:"第一Web・販売施工"},
  {id:"notebooklm",name:"NotebookLM",mark:"N",role:"資料参照・出典抽出（読取専用）"}
];
const LABELS={queued:"受付",planning:"判断中",waiting_approval:"承認待ち",running:"施工中",reviewing:"検査中",blocked:"停止・再判定",completed:"完了",failed:"失敗",cancelled:"中止"};
const initial=[{role:"zero",text:"AI5 HUBへようこそ。私、ゼロにだけ指示してください。Local APIが目的を整理し、必要な兄弟だけに振り分けます。",at:new Date().toISOString(),routed:[]}];
const load=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}};
const state={messages:load("ai5.messages",initial),taskIds:load("ai5.tasks",[]),reported:new Set(load("ai5.reported",[])),csrf:null,mode:"offline",activeTask:null,poll:null,agentStatus:{},installPrompt:null,installing:false,projects:[],projectCounts:{}};
const $=selector=>document.querySelector(selector);const agentsEl=$("#agents"),messagesEl=$("#messages"),composer=$("#composer"),promptEl=$("#prompt"),jobStatus=$("#jobStatus"),progress=$("#taskProgress"),resultDetails=$("#resultDetails"),approval=$("#approvalArea");
function escapeHtml(value=""){return String(value).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"})[c])}
function persist(){localStorage.setItem("ai5.messages",JSON.stringify(state.messages.slice(-100)));localStorage.setItem("ai5.tasks",JSON.stringify(state.taskIds.slice(-30)));localStorage.setItem("ai5.reported",JSON.stringify([...state.reported].slice(-30)))}
function agentName(id){return AGENTS.find(agent=>agent.id===id)?.name||id}
function renderMessages(){messagesEl.innerHTML=state.messages.map(message=>{const user=message.role==="user";const agent=AGENTS.find(a=>a.id===message.role);const avatar=user?"本人":agent?.mark||"0";const sender=user?"鉄兵":agent?.name||"Zero";const chips=(message.routed||[]).map(id=>`<span class="chip">${escapeHtml(agentName(id))}</span>`).join("");const time=new Date(message.at).toLocaleTimeString("ja-JP",{hour:"2-digit",minute:"2-digit"});return `<article class="message ${user?"user":""}"><span class="avatar">${escapeHtml(avatar)}</span><div><div class="meta sender">${escapeHtml(sender)}</div><div class="bubble">${escapeHtml(message.text).replace(/\n/g,"<br>")}${chips?`<div class="routing">${chips}</div>`:""}</div><div class="meta">${time}</div></div></article>`}).join("");messagesEl.scrollTop=messagesEl.scrollHeight}
function renderAgents(status={}){agentsEl.innerHTML=AGENTS.map(agent=>{const info=status[agent.id]||{state:"offline",connection:"not_connected"};const connection=info.connection==="mock"?"Mock接続":info.connection==="not_connected"?"未接続":"接続済";return `<div class="agent"><span class="avatar">${agent.mark}</span><span><b>${agent.name}</b><small>${agent.role}・${connection}</small></span><i class="status ${escapeHtml(info.state)}" title="${connection}"></i></div>`}).join("")}
function renderApproval(task){if(task.status!=="waiting_approval"){approval.className="approval-empty";approval.textContent="現在、本人確認が必要な操作はありません。";return}const review=task.approval?.zero_review||{};const ok=review.verdict==="APPROVAL_OK";const list=items=>(items||[]).map(item=>`<li>${escapeHtml(item)}</li>`).join("");approval.className=`approval-card ${ok?"recommended":"not-recommended"}`;approval.innerHTML=`<strong>Zero判定：${ok?"承認OK ✅":"承認非推奨 ⚠️"}</strong><p>${escapeHtml(review.reason||task.approval?.summary||"")}</p><b>リスク</b><ul>${list(review.risks)}</ul><b>確認済み事項</b><ul>${list(review.checks)}</ul><p>推奨：${ok?"承認して続行":"拒否して安全条件を修正"}</p><div><button data-action="approve">承認して続行</button><button data-action="cancel" class="danger">拒否</button></div><small>Zeroの判定は本人承認の代わりではありません。</small>`}
function renderTask(task){if(!task){jobStatus.className="job-card idle";jobStatus.innerHTML="<span>現在</span><b>指示待ち</b><small>ゼロにメッセージを送ってください</small>";progress.innerHTML="";resultDetails.hidden=true;renderApproval({status:"none"});renderAgents(state.agentStatus);return}state.activeTask=task;const routed=[task.assignedPrimary,...(task.assignedSecondary||[])];const live=structuredClone(state.agentStatus);if(live[task.assignedPrimary])live[task.assignedPrimary].state=({planning:"thinking",waiting_approval:"waiting",running:"running",reviewing:"thinking",blocked:"error",completed:"completed",failed:"error",cancelled:"ready"})[task.status]||"ready";renderAgents(live);jobStatus.className=`job-card ${task.status}`;jobStatus.innerHTML=`<span>${escapeHtml(LABELS[task.status]||task.status)}</span><b>${escapeHtml(task.objective)}</b><small>${escapeHtml(task.product_id||"")} / 担当: ${routed.map(agentName).join("・")} / Writer ${escapeHtml(task.writer||"NONE")}</small>`;progress.innerHTML=(task.timeline||[]).map((item,index,array)=>`<div class="progress-row ${index===array.length-1?"current":"done"}"><i></i><span><b>${escapeHtml(LABELS[item.status]||item.status)}</b><small>${escapeHtml(item.label)}</small></span></div>`).join("");const result=task.result;if(result){const files=(result.files_changed||result.filesChanged||result.changes||[]).join("、")||"なし";const tests=[...(result.tests||[]),...(result.qa||[])].join("、")||"記録なし";resultDetails.hidden=false;resultDetails.innerHTML=`<details><summary>結果・証拠・独立監査</summary><dl><dt>task_id</dt><dd>${escapeHtml(task.taskId)}</dd><dt>AI / verdict</dt><dd>${escapeHtml(result.ai||result.agent||"")} / ${escapeHtml(result.verdict||result.status||"")}</dd><dt>実施内容</dt><dd>${escapeHtml(result.summary||result.result||"")}</dd><dt>検査</dt><dd>${escapeHtml(tests)}</dd><dt>証拠</dt><dd>${escapeHtml((result.evidence||[]).join("、")||"なし")}</dd><dt>変更</dt><dd>${escapeHtml(files)}</dd><dt>commit</dt><dd>${escapeHtml(result.commit||result.commitId||"なし")}</dd><dt>Blocker</dt><dd>${escapeHtml((result.blockers||result.risks||[]).join("、")||"なし")}</dd><dt>独立監査</dt><dd>${escapeHtml(task.independent_audit?.ai||"—")} / ${escapeHtml(task.independent_audit?.status||"PENDING")}</dd><dt>retry</dt><dd>${task.retry_count||0} / ${task.max_attempts||0}</dd></dl></details>`}else resultDetails.hidden=true;renderApproval(task)}
async function api(path,options={}){const headers={"Content-Type":"application/json",...(options.headers||{})};if(state.csrf&&options.method&&options.method!=="GET")headers["X-AI5-CSRF"]=state.csrf;const response=await fetch(path,{...options,headers,credentials:"same-origin"});const value=await response.json();if(!response.ok){const error=new Error(value.error||`HTTP ${response.status}`);error.status=response.status;throw error}return value}
async function refreshTaskLists(){try{const data=await api('/api/tasks');const tasks=data.tasks||[];const terminal=['completed','failed','cancelled'];const card=t=>`<button data-task="${escapeHtml(t.taskId)}"><b>${escapeHtml(t.objective||t.title)}</b><small>${escapeHtml(LABELS[t.status]||t.status)}・${escapeHtml(t.assignedPrimary||t.assigned_agent||'')}</small></button>`;const active=tasks.filter(t=>!terminal.includes(t.status)&&t.status!=='waiting_approval');const waiting=tasks.filter(t=>t.status==='waiting_approval');const history=tasks.filter(t=>terminal.includes(t.status));state.waitingTaskId=waiting[0]?.taskId||null;$('#activeTasks').innerHTML=active.map(card).join('')||'<span class="empty">実行中の作業はありません。</span>';$('#historyTasks').innerHTML=history.map(card).join('')||'<span class="empty">履歴はありません。</span>';$('#approvalBadge').hidden=!waiting.length;$('#approvalBadge').textContent=waiting.length}catch{}}
function showAuth(message=""){state.mode="locked";$("#authGate").hidden=false;$("#authError").textContent=message;$("#connectionDot").className="online-dot error";$("#connectionText").textContent="本人認証が必要"}
async function bootstrap(){try{await api("/api/session");$("#authGate").hidden=true;const health=await api("/api/health");state.csrf=health.csrfToken;state.mode=health.mock?"mock":"live";$("#connectionDot").className="online-dot ready";$("#connectionText").textContent=`PCオンライン・Codex ${state.mode.toUpperCase()}`;const status=await api("/api/status");state.agentStatus=status.agents;renderAgents(status.agents);const latest=(status.tasks||[]).find(task=>state.taskIds.includes(task.taskId))||status.tasks?.[0];if(latest){renderTask(latest);watch(latest.taskId)}else renderTask(null)}catch(error){if(error.status===401){showAuth();return}state.mode="offline";$("#connectionDot").className="online-dot error";$("#connectionText").textContent="PCオフライン";renderAgents();jobStatus.innerHTML=`<span>OFFLINE</span><b>PCが現在オフラインです</b><small>タスクは送信されていません。接続後に自動復元します。</small>`}}
function zeroMessage(text,routed=[]){state.messages.push({role:"zero",text,at:new Date().toISOString(),routed});persist();renderMessages()}
function aiMessage(ai,text){state.messages.push({role:ai,text,at:new Date().toISOString(),routed:[]});persist();renderMessages()}
function notify(title,body){if('Notification'in window&&Notification.permission==='granted')new Notification(title,{body,icon:'/icons/ai5-icon-192.png',tag:'ai5-hub'})}
function report(task){if(state.reported.has(task.taskId))return;state.reported.add(task.taskId);const ai=task.result?.ai||task.assigned_ai||task.assignedPrimary;if(task.status==="completed"){aiMessage(ai,`${task.product_id||"Task"} 完了\n${task.result?.summary||task.result?.result||"担当作業完了"}\nPASS\nZeroへ返却しました`);zeroMessage(`${task.product_id||"Task"}を次工程候補へ昇格。\n独立監査: ${task.independent_audit?.status||"確認済み"}\nZero統合判定: PASS`,[ai,task.independent_audit?.ai].filter(Boolean));notify('AI5 HUB 完了',task.objective)}else if(["failed","blocked"].includes(task.status)){aiMessage(ai,`${task.product_id||"Task"} 結果\n${task.result?.summary||task.result?.result||task.errorType||"失敗"}\n${task.status.toUpperCase()}\nZeroへ返却しました`);zeroMessage(`通常FAILを回収しました。retry ${task.retry_count||0}/${task.max_attempts||0}。Fallbackまたは再施工を判定します。`);if(task.canonical_status==="ESCALATED")notify('AI5 HUB 重大失敗',task.objective)}else if(task.status==="cancelled")zeroMessage("タスクを中止しました。");persist()}
async function refreshTask(id){try{const task=await api(`/api/tasks/${id}`);renderTask(task);if(["completed","failed","blocked","cancelled"].includes(task.status)){clearInterval(state.poll);state.poll=null;report(task)}return task}catch(error){jobStatus.innerHTML=`<span>ERROR</span><b>状態取得失敗</b><small>${escapeHtml(error.message)}</small>`}}
function watch(id){if(state.poll)clearInterval(state.poll);refreshTask(id);state.poll=setInterval(()=>refreshTask(id),650)}
composer.addEventListener("submit",async event=>{event.preventDefault();const text=promptEl.value.trim();if(!text||state.mode==="offline")return;composer.classList.add("sending");state.messages.push({role:"user",text,at:new Date().toISOString(),routed:[]});promptEl.value="";persist();renderMessages();try{const key=crypto.randomUUID();const task=await api("/api/tasks",{method:"POST",headers:{"Idempotency-Key":key},body:JSON.stringify({message:text,source:"teppei",priority:"normal",conversationId:"local-default"})});if(!state.taskIds.includes(task.taskId))state.taskIds.push(task.taskId);const routed=[task.assignedPrimary,...(task.assignedSecondary||[])];zeroMessage(task.requiresApproval?`了解。${routed.map(agentName).join("・")}へ振り分けましたが、重大操作を含むため承認待ちです。`:`了解。目的と完了条件を整理し、${routed.map(agentName).join("・")}へ振り分けました。施工を開始します。`,routed);renderTask(task);watch(task.taskId)}catch(error){zeroMessage(`受付に失敗しました: ${error.message}`)}finally{composer.classList.remove("sending")}});
approval.addEventListener("click",async event=>{const action=event.target.dataset.action;if(!action||!state.activeTask)return;if(state.poll){clearInterval(state.poll);state.poll=null}try{let body="{}";if(action==="approve"){const challenge=await api(`/api/tasks/${state.activeTask.taskId}/approval-challenge`,{method:"POST",body:"{}"});body=JSON.stringify({approvalToken:challenge.approvalToken})}const task=await api(`/api/tasks/${state.activeTask.taskId}/${action}`,{method:"POST",body});renderTask(task);watch(task.taskId)}catch(error){zeroMessage(`承認操作に失敗しました: ${error.message}`);watch(state.activeTask.taskId)}});
promptEl.addEventListener("input",()=>{promptEl.style.height="auto";promptEl.style.height=`${Math.min(promptEl.scrollHeight,140)}px`});$("#flowButton").addEventListener("click",()=>$("#activity").classList.add("open"));$("#closeFlow").addEventListener("click",()=>$("#activity").classList.remove("open"));
$("#loginButton").addEventListener("click",async()=>{try{await api("/api/session",{method:"POST",body:"{}"});await bootstrap()}catch(error){showAuth(error.message==="authentication_failed"?"Tailscaleで本人確認できませんでした。":"PCへ接続できません。")}});
$("#logoutButton").addEventListener("click",async()=>{try{await api("/api/logout",{method:"POST",body:"{}"})}catch{}showAuth("ログアウトしました。")});
$("#notifyButton").addEventListener("click",async()=>{if(!('Notification'in window)){zeroMessage('この端末は通知に対応していません。');return}const permission=await Notification.requestPermission();zeroMessage(permission==='granted'?'完了・承認待ち・重大失敗だけ通知します。':'通知は許可されませんでした。')});
window.addEventListener('beforeinstallprompt',event=>{event.preventDefault();state.installPrompt=event;$('#installButton').hidden=false});
async function pwaDiagnostics(){const chrome=/Chrome\//.test(navigator.userAgent)&&!/; wv\)/.test(navigator.userAgent);const standalone=matchMedia('(display-mode: standalone)').matches;let registration=null;let manifest='NG';let installed='取得不可';try{registration=await navigator.serviceWorker?.getRegistration('/');const response=await fetch('/manifest.webmanifest',{cache:'no-store'});manifest=response.ok?'OK':`NG (${response.status})`;if(navigator.getInstalledRelatedApps){const apps=await navigator.getInstalledRelatedApps();installed=apps.some(app=>app.platform==='webapp')?'WebAPK登録あり':'WebAPK登録なし'}}catch{}return `PWA診断 v35\nHTTPS: ${isSecureContext?'OK':'NG'}\nChrome本体: ${chrome?'OK':'NG（Gmail等の内蔵ブラウザでは不可）'}\nmanifest: ${manifest}\nService Worker: ${registration?.active?'OK':registration?'準備中':'NG'}\nChrome WebAPK: ${installed}\nアプリ表示: ${standalone?'standalone':'ブラウザ'}\nインストール候補: ${state.installPrompt?'OK':'NG'}`}
$('#diagnoseButton').addEventListener('click',async()=>zeroMessage(await pwaDiagnostics()));
$('#installButton').addEventListener('click',async()=>{if(state.installing)return;if(!state.installPrompt){zeroMessage(await pwaDiagnostics());return}state.installing=true;$('#installButton').disabled=true;try{state.installPrompt.prompt();const choice=await state.installPrompt.userChoice;state.installPrompt=null;$('#installButton').hidden=true;zeroMessage(choice.outcome==='accepted'?'Chromeがインストール要求を受け付けました。Android OSへの登録完了を確認してください。':'インストールを中止しました。')}finally{state.installing=false;$('#installButton').disabled=false}});
window.addEventListener('appinstalled',()=>{state.installPrompt=null;$('#installButton').hidden=true;zeroMessage('Chromeがインストール要求を受け付けました。Androidのホーム画面と設定→アプリへの登録確認が必要です。')});
const fmtJst=value=>value?new Intl.DateTimeFormat('ja-JP',{timeZone:'Asia/Tokyo',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}).format(new Date(value)):'—';
const stoppedFor=value=>{if(!value)return'—';const mins=Math.max(0,Math.floor((Date.now()-new Date(value))/60000));return mins<60?`${mins}分`:`${Math.floor(mins/60)}h ${mins%60}m`};
const priority=p=>p.stopCode==='ERROR_LOOP_STOP'||p.status==='FAILED'?0:p.blockedBy==='TEPPEI'?1:['ALL_AI_DONE_BUT_IDLE','NEXT_STEP_MISSING'].includes(p.stopCode)?2:p.blockedBy==='CODEX'?3:p.blockedBy==='ZERO'?4:p.status==='RUNNING'?6:p.phase==='RELEASE_READY'?7:['PUBLISHED','OPERATING'].includes(p.phase)?8:p.phase==='ARCHIVED'?10:5;
function projectVisible(p){const q=$('#projectSearch').value.trim().toLowerCase(),f=$('#projectFilter').value;if(q&&!`${p.name} ${p.repository?.name||''}`.toLowerCase().includes(q))return false;if(f==='all')return true;if(f==='autoOn')return p.autoExecution.enabled;if(f==='autoOff')return!p.autoExecution.enabled;if(f==='error')return p.status==='FAILED'||['ERROR_LOOP_STOP','CREDIT_PROTECTION_STOP'].includes(p.stopCode);if(f==='running')return p.status==='RUNNING';if(f==='selling')return['PUBLISHED','OPERATING'].includes(p.phase);return p.blockedBy===f||p.phase===f}
function renderProjects(){const c=state.projectCounts;$('#projectStats').innerHTML=[['🟢','進行中',c.running],['🔵','AI施工中',c.aiRunning],['🟠','停止',c.stopped],['🟣','本人待ち',c.human],['🔴','異常',c.error],['🟡','販売準備',c.release],['💰','販売中',c.selling],['✅','完了',c.completed]].map(x=>`<div><span>${x[0]} ${x[1]}</span><b>${x[2]||0}</b></div>`).join('')+`<div class="auto-total"><span>AUTO ACTIVE ${c.autoOn||0}</span><b>OFF ${c.autoOff||0}</b></div>`;const list=state.projects.filter(projectVisible).sort((a,b)=>priority(a)-priority(b));$('#projectList').innerHTML=list.map(p=>`<article class="project-card mode-${escapeHtml(p.autoExecution.mode||'OFF')}" data-project="${escapeHtml(p.projectId)}"><button class="project-open"><small>${escapeHtml(p.phase)}</small><h3>${escapeHtml(p.name)}</h3><strong class="stop-${escapeHtml(p.stopCode)}">${p.stopCode==='ALL_AI_DONE_BUT_IDLE'?'🟠 次工程未投入':escapeHtml(p.blockedBy==='NONE'?p.status:`${p.blockedBy} WAITING`)}</strong><dl><dt>停止</dt><dd>${fmtJst(p.timestamps.stoppedAt)}</dd><dt>停止時間</dt><dd>${stoppedFor(p.timestamps.stoppedAt)}</dd><dt>次</dt><dd>${escapeHtml(p.nextAction||'未設定')}</dd><dt>Codex / Zero</dt><dd>${escapeHtml(p.aiState.codex)} / ${escapeHtml(p.aiState.zero)}</dd><dt>GitHub</dt><dd>${escapeHtml(p.repository.sync?.state||'UNKNOWN')} ${escapeHtml((p.repository.latestCommit||'UNLINKED').slice(0,8))}</dd></dl></button><label class="auto-switch">AUTO EXECUTION <select data-auto="${escapeHtml(p.projectId)}"><option ${p.autoExecution.mode==='OFF'?'selected':''}>OFF</option><option value="DRY_RUN" ${p.autoExecution.mode==='DRY_RUN'?'selected':''}>DRY RUN</option><option value="LIVE" ${p.autoExecution.mode==='LIVE'?'selected':''}>LIVE</option></select></label></article>`).join('')||'<p class="project-empty">該当Projectはありません。</p>'}
function renderSalesFactory(){const products=state.projects.filter(p=>/^sales-m[1-5]-/.test(p.projectId));$('#salesFactory').innerHTML=products.map(p=>`<article class="factory-card"><header><b>${escapeHtml(p.productId||p.projectId)}</b><span>${escapeHtml(p.phase)}</span></header><h4>${escapeHtml(p.name)}</h4><progress max="100" value="${Number(p.progress||0)}"></progress><dl><dt>Primary</dt><dd>${escapeHtml(p.primaryAI||'—')}</dd><dt>Writer</dt><dd>${escapeHtml(p.writer||'NONE')}</dd><dt>Task</dt><dd>${escapeHtml(p.currentTask||'—')}</dd><dt>Result</dt><dd>${escapeHtml(p.lastResult||p.execution?.lastResult||'—')}</dd><dt>QA / Audit</dt><dd>${escapeHtml(p.qualityGate?.qa||p.qualityGate?.tests||'UNKNOWN')} / ${escapeHtml(p.qualityGate?.audit||p.qualityGate?.review||'UNKNOWN')}</dd><dt>Blocker</dt><dd>${escapeHtml(p.stopReason||p.blockedBy||'NONE')}</dd><dt>Approval</dt><dd>${escapeHtml(p.approval?.status||'NONE')}</dd><dt>Next</dt><dd>${escapeHtml(p.nextAction||'—')}</dd></dl><small>${escapeHtml((p.repository?.latestCommit||'').slice(0,8))}・${escapeHtml(p.timestamps?.updatedAt||'')}</small></article>`).join('')||'<p class="project-empty">M1〜M5未登録</p>'}
async function refreshProjects(){try{const data=await api('/api/projects');state.projects=data.projects||[];state.projectCounts=data.counts||{};renderProjects();renderSalesFactory()}catch(error){$('#projectList').innerHTML=`<p class="project-empty">状態取得失敗: ${escapeHtml(error.message)}</p>`}}
function openProject(p){const history=(p.history||[]).slice().reverse().map(h=>`<li><time>${fmtJst(h.at)}</time><b>${escapeHtml(h.actor||'SYSTEM')} ${escapeHtml(h.type)}</b><span>${escapeHtml(h.detail||'')}</span></li>`).join('');$('#projectDetail').innerHTML=`<small>PROJECT CONTROL</small><h2>${escapeHtml(p.name)}</h2><div class="detail-badges"><b>${escapeHtml(p.phase)}</b><b>${escapeHtml(p.status)}</b><b>${escapeHtml(p.blockedBy)}</b></div><dl class="project-detail-grid"><dt>停止理由</dt><dd>${escapeHtml(p.stopReason||p.stopCode)}</dd><dt>停止日時</dt><dd>${fmtJst(p.timestamps.stoppedAt)}</dd><dt>再開日時</dt><dd>${fmtJst(p.timestamps.resumedAt)}</dd><dt>作業開始</dt><dd>${fmtJst(p.timestamps.workStartedAt)}</dd><dt>作業完了</dt><dd>${fmtJst(p.timestamps.workCompletedAt)}</dd><dt>Repository</dt><dd>${escapeHtml(p.repository.owner?`${p.repository.owner}/${p.repository.name}`:p.repository.name||'UNLINKED')}</dd><dt>branch / commit</dt><dd>${escapeHtml(p.repository.activeBranch||'—')} / ${escapeHtml((p.repository.latestCommit||'—').slice(0,8))}</dd><dt>品質</dt><dd>tests ${escapeHtml(p.qualityGate.tests)} / review ${escapeHtml(p.qualityGate.review)} / field ${escapeHtml(p.qualityGate.fieldValidation)}</dd><dt>次の一手</dt><dd>${escapeHtml(p.nextAction||'未設定')}</dd><dt>Cost / retry</dt><dd>${escapeHtml(p.executionPolicy.costClass)} / ${p.executionPolicy.retryCount||0} of ${p.executionPolicy.maxRetry}</dd></dl><h3>AI STATE</h3><div class="ai-state">${Object.entries(p.aiState).map(([k,v])=>`<span>${escapeHtml(k)}<b>${escapeHtml(v)}</b></span>`).join('')}</div><h3>TIMELINE</h3><ol class="project-timeline">${history||'<li>履歴なし</li>'}</ol>`;$('#projectDialog').showModal()}
$('#projectList').addEventListener('change',async event=>{const auto=event.target.closest('[data-auto]');if(!auto)return;event.stopPropagation();try{await api(`/api/projects/${auto.dataset.auto}/auto-execution`,{method:'POST',body:JSON.stringify({mode:auto.value})});await refreshProjects()}catch(error){zeroMessage(`AUTO切替失敗: ${error.message}`);await refreshProjects()}});$('#projectList').addEventListener('click',async event=>{if(event.target.closest('[data-auto]'))return;const id=event.target.closest('[data-project]')?.dataset.project;if(id){const p=await api(`/api/projects/${id}`);openProject(p)}});
$('#projectSearch').addEventListener('input',renderProjects);$('#projectFilter').addEventListener('change',renderProjects);$('#addProjectButton').addEventListener('click',()=>$('#projectCreateDialog').showModal());$('[data-close-project]').addEventListener('click',()=>$('#projectCreateDialog').close());$('#projectCreateForm').addEventListener('submit',async event=>{event.preventDefault();const body=Object.fromEntries(new FormData(event.target));try{await api('/api/projects',{method:'POST',body:JSON.stringify(body)});event.target.reset();$('#projectCreateDialog').close();await refreshProjects()}catch(error){zeroMessage(`Project登録失敗: ${error.message}`)}});
async function refreshSystem(){try{const s=await api('/api/projects/system');$('#systemStatus').innerHTML=Object.entries({Scheduler:s.scheduler.status,'Last Scan':fmtJst(s.scheduler.lastScan),'Next Scan':fmtJst(s.scheduler.nextScan),Bridge:s.bridge.available?'READY':'STOPPED','GitHub Sync':state.projects.map(p=>p.repository.sync?.state||'UNKNOWN').join(' / '),'Active Project Lock':s.locks.length,'Codex Queue':s.queue,'AUTO LIVE':s.autoLive,'DRY RUN':s.dryRun,'Credit Stops':s.creditStops,'Approval Stops':s.approvalStops}).map(([k,v])=>`<div><span>${escapeHtml(k)}</span><b>${escapeHtml(v)}</b></div>`).join('')}catch(error){$('#systemStatus').textContent=`SYSTEM取得失敗: ${error.message}`}}$('#scanProjectsButton').addEventListener('click',async()=>{try{await api('/api/projects/scan',{method:'POST',body:JSON.stringify({fetch:true,dryRun:false})});await refreshProjects();await refreshSystem()}catch(error){zeroMessage(`巡回失敗: ${error.message}`)}});
document.querySelectorAll('.bottom-nav button').forEach(button=>button.addEventListener('click',async()=>{document.querySelectorAll('.bottom-nav button').forEach(item=>item.classList.toggle('active',item===button));const view=button.dataset.view,projects=view==='projects',system=view==='system';$('#projectsView').hidden=!projects;$('#systemView').hidden=!system;messagesEl.hidden=projects||system;composer.hidden=projects||system;$('#activity').classList.remove('mobile-open');if(view==='zero')return;if(projects){await refreshProjects();return}if(system){await refreshProjects();await refreshSystem()}}));
$('#taskLists').addEventListener('click',event=>{const id=event.target.closest('[data-task]')?.dataset.task;if(id){refreshTask(id);watch(id)}});
window.addEventListener("offline",()=>{$("#connectionDot").className="online-dot error";$("#connectionText").textContent="通信切断・施工はPCで継続中"});
window.addEventListener("online",()=>bootstrap());
if("serviceWorker" in navigator)navigator.serviceWorker.register("/service-worker.js?v=35",{scope:"/"}).then(()=>navigator.serviceWorker.ready).catch(error=>{console.error('AI5 HUB service worker registration failed',error);zeroMessage(`PWA初期化に失敗しました: ${error.message}`)});
setInterval(refreshTaskLists,3000);
renderMessages();renderAgents();bootstrap();refreshTaskLists();
