$ErrorActionPreference='Stop'
$global:AI5TestRoot=Join-Path $PSScriptRoot 'server\tests'
$code=Get-Content -Raw -Encoding UTF8 (Join-Path $global:AI5TestRoot 'phase1.tests.ps1')
& ([ScriptBlock]::Create($code))
& (Join-Path $global:AI5TestRoot 'Phase2.Tests.ps1')
& (Join-Path $global:AI5TestRoot 'MobileSecurity.Tests.ps1')
& (Join-Path $global:AI5TestRoot 'TaskEngine.Tests.ps1')
& (Join-Path $global:AI5TestRoot 'PwaInstallability.Tests.ps1')
& (Join-Path $global:AI5TestRoot 'ZeroApproval.Tests.ps1')
& (Join-Path $global:AI5TestRoot 'NotebookLMAdapter.Tests.ps1')
& (Join-Path $global:AI5TestRoot 'ProjectControl.Tests.ps1')
& (Join-Path $global:AI5TestRoot 'ProjectAutoExecution.Tests.ps1')
& (Join-Path $global:AI5TestRoot 'SalesFactoryV6.Tests.ps1')
& (Join-Path $global:AI5TestRoot 'RepositoryWriterLock.Tests.ps1')
& (Join-Path $global:AI5TestRoot 'ZeroReturn.Tests.ps1')
& (Join-Path $global:AI5TestRoot 'CapabilityPolicy.Tests.ps1')
& (Join-Path $global:AI5TestRoot 'SourceOfTruth.Tests.ps1')
& (Join-Path $global:AI5TestRoot 'EvidenceStore.Tests.ps1')
