$ErrorActionPreference='Stop'
$global:AI5TestRoot=Join-Path $PSScriptRoot 'server\tests'
$code=Get-Content -Raw -Encoding UTF8 (Join-Path $global:AI5TestRoot 'phase1.tests.ps1')
& ([ScriptBlock]::Create($code))
& (Join-Path $global:AI5TestRoot 'Phase2.Tests.ps1')
& (Join-Path $global:AI5TestRoot 'MobileSecurity.Tests.ps1')
& (Join-Path $global:AI5TestRoot 'TaskEngine.Tests.ps1')
& (Join-Path $global:AI5TestRoot 'PwaInstallability.Tests.ps1')
& (Join-Path $global:AI5TestRoot 'ZeroApproval.Tests.ps1')
& (Join-Path $global:AI5TestRoot 'NotebookLMAdapter.Tests.ps1')
& (Join-Path $global:AI5TestRoot 'ExecutionPolicy.Tests.ps1')
& (Join-Path $global:AI5TestRoot 'BrowserSpecialistAdapter.Tests.ps1')
& (Join-Path $global:AI5TestRoot 'ManusAdapter.Tests.ps1')
& (Join-Path $global:AI5TestRoot 'SpecialistRegistry.Tests.ps1')
& (Join-Path $global:AI5TestRoot 'ManusMeasuredHealth.Tests.ps1')
& (Join-Path $global:AI5TestRoot 'ManusResultRecovery.Tests.ps1')
& (Join-Path $global:AI5TestRoot 'NotificationUi.Tests.ps1')
& (Join-Path $global:AI5TestRoot 'Phase3ApiE2E.Tests.ps1')
& (Join-Path $global:AI5TestRoot 'ProjectControl.Tests.ps1')
& (Join-Path $global:AI5TestRoot 'ProjectAutoExecution.Tests.ps1')
& (Join-Path $global:AI5TestRoot 'Utf8Bridge.Tests.ps1')
& (Join-Path $global:AI5TestRoot 'BridgeRetry.Tests.ps1')
& (Join-Path $global:AI5TestRoot 'PushNotification.Tests.ps1')
& (Join-Path $global:AI5TestRoot 'CommandCenter.Tests.ps1')
& (Join-Path $global:AI5TestRoot 'CommandCenterResponsive.Tests.ps1')
& (Join-Path $global:AI5TestRoot 'ApprovalNotificationSchedule.Tests.ps1')
& (Join-Path $global:AI5TestRoot 'AutonomousLoop.Tests.ps1')
& (Join-Path $global:AI5TestRoot 'Attachments.Tests.ps1')
