param([int]$Port=43125,[string]$HostName='127.0.0.1')
$ErrorActionPreference='Stop'
$ServerRoot=if($global:AI5ServerRoot){$global:AI5ServerRoot}else{$PSScriptRoot};$AppRoot=Split-Path $ServerRoot
foreach($module in @('router\Router.ps1','adapters\MockAdapter.ps1','storage\Store.ps1','security\Security.ps1')){. ([ScriptBlock]::Create((Get-Content -Raw -Encoding UTF8 (Join-Path $ServerRoot $module))))}
Initialize-AI5Store $ServerRoot;$Mock=if($env:AI5_MOCK){$env:AI5_MOCK-ne'false'}else{$true};$Csrf=[guid]::NewGuid().ToString('N')
$listener=[Net.Sockets.TcpListener]::new([Net.IPAddress]::Parse($HostName),$Port);$listener.Start();Write-Host "AI5 HUB: http://$HostName`:$Port/ (mock=$Mock)"
function Send-Response($stream,[int]$status,[string]$type,[byte[]]$bytes){$names=@{200='OK';202='Accepted';400='Bad Request';403='Forbidden';404='Not Found';409='Conflict';500='Internal Server Error'};$head="HTTP/1.1 $status $($names[$status])`r`nContent-Type: $type`r`nContent-Length: $($bytes.Length)`r`nCache-Control: no-store`r`nConnection: close`r`n`r`n";$header=[Text.Encoding]::ASCII.GetBytes($head);$stream.Write($header,0,$header.Length);$stream.Write($bytes,0,$bytes.Length);$stream.Flush()}
function Send-Json($stream,$value,[int]$status=200){$bytes=[Text.Encoding]::UTF8.GetBytes(($value|ConvertTo-Json -Depth 15));Send-Response $stream $status 'application/json; charset=utf-8' $bytes}
function Send-Static($stream,[string]$path){$relative=if($path-eq'/'){'index.html'}else{$path.TrimStart('/')};$full=[IO.Path]::GetFullPath((Join-Path $AppRoot $relative));if(!$full.StartsWith([IO.Path]::GetFullPath($AppRoot))-or!(Test-Path $full)){Send-Json $stream @{error='not_found'} 404;return};$types=@{'.html'='text/html; charset=utf-8';'.js'='text/javascript; charset=utf-8';'.css'='text/css; charset=utf-8';'.json'='application/json; charset=utf-8'};Send-Response $stream 200 $types[[IO.Path]::GetExtension($full)] ([IO.File]::ReadAllBytes($full))}
function Read-Request($stream){$headerBytes=[Collections.Generic.List[byte]]::new();$tail=@();while($true){$value=$stream.ReadByte();if($value-lt0){return $null};$headerBytes.Add([byte]$value);$tail=@($tail+[byte]$value|Select-Object -Last 4);if($tail.Count-eq4-and$tail[0]-eq13-and$tail[1]-eq10-and$tail[2]-eq13-and$tail[3]-eq10){break};if($headerBytes.Count-gt65536){throw'headers_too_large'}};$lines=([Text.Encoding]::ASCII.GetString($headerBytes.ToArray())).Split(@("`r`n"),[StringSplitOptions]::None);$parts=$lines[0].Split(' ');$headers=@{};foreach($line in $lines[1..($lines.Count-1)]){$index=$line.IndexOf(':');if($index-gt0){$headers[$line.Substring(0,$index).Trim()]=$line.Substring($index+1).Trim()}};$length=0;if($headers.ContainsKey('Content-Length')){[int]::TryParse($headers['Content-Length'],[ref]$length)|Out-Null};$bodyBytes=New-Object byte[] $length;$read=0;while($read-lt$length){$count=$stream.Read($bodyBytes,$read,$length-$read);if($count-le0){break};$read+=$count};$body=if($read-gt0){[Text.Encoding]::UTF8.GetString($bodyBytes,0,$read)}else{''};[pscustomobject]@{Method=$parts[0];Path=([uri]("http://local"+$parts[1])).AbsolutePath;Headers=$headers;Body=$body}}
function Parse-Body($request){if($request.Body){$request.Body|ConvertFrom-Json}else{[pscustomobject]@{}}}
function Update-State($task,[string]$status,[string]$label){$task.status=$status;$task.timeline+=,[ordered]@{status=$status;label=$label;at=[DateTime]::UtcNow.ToString('o')};Save-AI5Task $task}
function Execute-Mock($task){Update-State $task 'planning' 'Zeroが目的・担当・完了条件を確認';Update-State $task 'running' "$($task.assignedPrimary) Mockが施工";$task.result=Invoke-AI5MockAdapter $task;Update-State $task 'reviewing' 'Zeroが結果を検査';Update-State $task 'completed' '完了条件を確認';Write-AI5Log 'tasks' 'task_completed' @{task_id=$task.taskId;status='completed';adapter='mock'}}
function New-Task($body,[string]$idem){$route=Get-AI5Route $body.message;$id='task_'+[guid]::NewGuid().ToString('N').Substring(0,12);[pscustomobject][ordered]@{taskId=$id;conversationId=$body.conversationId;message=Protect-AI5Text $body.message;objective=$route.objective;source=$(if($body.source){$body.source}else{'teppei'});priority=$(if($body.priority){$body.priority}else{'normal'});status=$(if($route.requiresApproval){'waiting_approval'}else{'queued'});assignedPrimary=$route.primary;assignedSecondary=$route.secondary;requiresApproval=$route.requiresApproval;approval=$(if($route.requiresApproval){[ordered]@{type=$route.approvalType;summary='重大操作を含むため本人承認が必要です';status='pending'}}else{$null});route=$route;result=$null;timeline=@([ordered]@{status='queued';label='Local APIが受付';at=[DateTime]::UtcNow.ToString('o')});idempotencyKey=$idem;createdAt=[DateTime]::UtcNow.ToString('o');updatedAt=[DateTime]::UtcNow.ToString('o')}}
try{while($true){$client=$listener.AcceptTcpClient();$stream=$client.GetStream();try{$request=Read-Request $stream;if(!$request){continue};$path=$request.Path;$method=$request.Method;if($path.StartsWith('/api/')-and$method-ne'GET'-and$Csrf-ne$request.Headers['X-AI5-CSRF']){Write-AI5Log 'security' 'csrf_rejected' @{path=$path};Send-Json $stream @{error='csrf'} 403;continue}
  if($method-eq'GET'-and$path-eq'/api/health'){Send-Json $stream @{ok=$true;service='ai5-hub';mock=$Mock;csrfToken=$Csrf;time=[DateTime]::UtcNow.ToString('o')};continue}
  if($method-eq'GET'-and$path-eq'/api/status'){$state=if($Mock){'ready'}else{'offline'};Send-Json $stream @{mode=$(if($Mock){'mock'}else{'live'});agents=@{zero=@{state='ready';connection='local'};codex=@{state=$state;connection=$(if($Mock){'mock'}else{'not_connected'})};gemini=@{state=$state;connection=$(if($Mock){'mock'}else{'not_connected'})};claude=@{state=$state;connection=$(if($Mock){'mock'}else{'not_connected'})};manus=@{state=$state;connection=$(if($Mock){'mock'}else{'not_connected'})}};tasks=@(Get-AI5Tasks)};continue}
  if($method-eq'POST'-and$path-eq'/api/tasks'){$body=Parse-Body $request;$problem=Test-AI5Instruction $body.message;if($problem){Send-Json $stream @{error=$problem} 400;continue};$idem=$request.Headers['Idempotency-Key'];if($idem){$existing=Get-AI5Tasks|Where-Object{$_.idempotencyKey-eq$idem}|Select-Object -First 1;if($existing){Send-Json $stream $existing;continue}};$task=New-Task $body $idem;if($task.requiresApproval){$task.timeline+=,[ordered]@{status='waiting_approval';label='本人承認待ち';at=[DateTime]::UtcNow.ToString('o')}};Save-AI5Task $task;Write-AI5Log 'tasks' 'task_created' @{task_id=$task.taskId;primary=$task.assignedPrimary;approval=$task.requiresApproval};Send-Json $stream $task 202;if(!$task.requiresApproval){Execute-Mock $task};continue}
  if($path-match'^/api/tasks/([^/]+)$'-and$method-eq'GET'){$task=Get-AI5Task $Matches[1];if($task){Send-Json $stream $task}else{Send-Json $stream @{error='not_found'} 404};continue}
  if($path-match'^/api/tasks/([^/]+)/approve$'-and$method-eq'POST'){$task=Get-AI5Task $Matches[1];if(!$task){Send-Json $stream @{error='not_found'} 404;continue};if($task.status-ne'waiting_approval'){Send-Json $stream @{error='invalid_state'} 409;continue};$task.approval.status='approved';Update-State $task 'queued' '本人が承認';Send-Json $stream $task;Execute-Mock $task;continue}
  if($path-match'^/api/tasks/([^/]+)/cancel$'-and$method-eq'POST'){$task=Get-AI5Task $Matches[1];if(!$task){Send-Json $stream @{error='not_found'} 404;continue};if($task.status-in@('completed','failed','cancelled')){Send-Json $stream @{error='invalid_state'} 409;continue};Update-State $task 'cancelled' '本人が中止';Send-Json $stream $task;continue}
  if($path.StartsWith('/api/')){Send-Json $stream @{error='not_found'} 404}else{Send-Static $stream $path}
}catch{Write-AI5Log 'errors' 'request_failed' @{error=$_.Exception.Message};try{Send-Json $stream @{error='internal_error'} 500}catch{}}finally{$stream.Dispose();$client.Dispose()}}}finally{$listener.Stop()}
