import{mkdir,open,readFile,rename,rm}from'node:fs/promises';import{dirname}from'node:path';
const delay=ms=>new Promise(resolve=>setTimeout(resolve,ms));
export class DurableFileLedger{
 constructor(file,{lockTimeoutMs=2000,staleLockMs=30000}={}){this.file=file;this.lock=`${file}.lock`;this.lockTimeoutMs=lockTimeoutMs;this.staleLockMs=staleLockMs;this.records=null;this.queue=Promise.resolve();}
 async #load(){if(this.records)return;await mkdir(dirname(this.file),{recursive:true});try{const value=JSON.parse(await readFile(this.file,'utf8'));if(value.version!==1||!value.records||typeof value.records!=='object')throw new Error('invalid ledger schema');this.records=new Map(Object.entries(value.records));}catch(error){if(error.code==='ENOENT')this.records=new Map();else throw new Error(`ledger recovery refused: ${error.message}`);}}
 async #acquire(){const started=Date.now();for(;;)try{const handle=await open(this.lock,'wx',0o600);await handle.writeFile(JSON.stringify({pid:process.pid,createdAt:Date.now()}));return handle;}catch(error){if(error.code!=='EEXIST')throw error;try{const value=JSON.parse(await readFile(this.lock,'utf8'));if(Date.now()-Number(value.createdAt)>this.staleLockMs){await rm(this.lock,{force:true});continue;}}catch{}if(Date.now()-started>=this.lockTimeoutMs)throw new Error('ledger lock timeout');await delay(20);}}
 async #release(handle){try{await handle.close();}finally{await rm(this.lock,{force:true});}}
 async get(fingerprint){await this.queue;await this.#load();return this.records.get(fingerprint);}
 async put(fingerprint,identity,response){const operation=async()=>{await this.#load();const handle=await this.#acquire();try{this.records=null;await this.#load();const prior=this.records.get(fingerprint);if(prior&&prior.identity!==identity)throw Object.assign(new Error('purchase token replay mismatch'),{status:409});this.records.set(fingerprint,{identity,response});const temp=`${this.file}.${process.pid}.${Date.now()}.tmp`,payload=JSON.stringify({version:1,records:Object.fromEntries(this.records)}),out=await open(temp,'wx',0o600);try{await out.writeFile(payload);await out.sync();}finally{await out.close();}await rename(temp,this.file);}finally{await this.#release(handle);}};this.queue=this.queue.then(operation,operation);return this.queue;}
}
