import {readFile} from'node:fs/promises';import{createSign}from'node:crypto';
const b64=value=>Buffer.from(typeof value==='string'?value:JSON.stringify(value)).toString('base64url');
export class GooglePlayVerifier{
 constructor({credentialsFile,packageName,basePlanId='',fetchImpl=fetch,clock=()=>Date.now()}){this.credentialsFile=credentialsFile;this.packageName=packageName;this.basePlanId=basePlanId;this.fetch=fetchImpl;this.clock=clock;this.cached=null;}
 async #accessToken(){if(this.cached&&this.cached.expiresAt>this.clock()+60000)return this.cached.value;const credentials=JSON.parse(await readFile(this.credentialsFile,'utf8'));
  if(!credentials.client_email||!credentials.private_key||!credentials.token_uri)throw new Error('invalid Google service-account credentials');
  const now=Math.floor(this.clock()/1000),unsigned=`${b64({alg:'RS256',typ:'JWT'})}.${b64({iss:credentials.client_email,scope:'https://www.googleapis.com/auth/androidpublisher',aud:credentials.token_uri,iat:now,exp:now+3600})}`,signer=createSign('RSA-SHA256');signer.update(unsigned);signer.end();const assertion=`${unsigned}.${signer.sign(credentials.private_key,'base64url')}`;
  const response=await this.fetch(credentials.token_uri,{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'urn:ietf:params:oauth:grant-type:jwt-bearer',assertion})});
  if(!response.ok)throw new Error(`Google OAuth failed (${response.status})`);const token=await response.json();if(!token.access_token)throw new Error('Google OAuth response missing access token');this.cached={value:token.access_token,expiresAt:this.clock()+Number(token.expires_in||3600)*1000};return this.cached.value;
 }
 async verify({purchaseToken,productId,packageName}){if(packageName!==this.packageName)throw Object.assign(new Error('package mismatch'),{status:403});const accessToken=await this.#accessToken(),url=`https://androidpublisher.googleapis.com/androidpublisher/v3/applications/${encodeURIComponent(packageName)}/purchases/subscriptionsv2/tokens/${encodeURIComponent(purchaseToken)}`,response=await this.fetch(url,{headers:{authorization:`Bearer ${accessToken}`}});
  if(response.status===404)throw Object.assign(new Error('purchase not found'),{status:404});if(!response.ok)throw new Error(`Google Play verification failed (${response.status})`);const value=await response.json(),lines=Array.isArray(value.lineItems)?value.lineItems:[],line=lines.find(item=>item.productId===productId);if(!line)throw Object.assign(new Error('verified product mismatch'),{status:403});if(this.basePlanId&&line.offerDetails?.basePlanId!==this.basePlanId)throw Object.assign(new Error('verified base plan mismatch'),{status:403});
  const subscriptionState=String(value.subscriptionState||''),cancelReason=value.canceledStateContext?Object.keys(value.canceledStateContext)[0]||'CANCELED':null;
  return{productId,packageName,expiryTimeMillis:Date.parse(line.expiryTime||''),acknowledged:value.acknowledgementState==='ACKNOWLEDGEMENT_STATE_ACKNOWLEDGED',autoRenewing:Boolean(line.autoRenewingPlan?.autoRenewEnabled),paymentState:subscriptionState.includes('PENDING')?'PENDING':'PAID',onHold:subscriptionState.includes('ON_HOLD')||subscriptionState.includes('PAUSED'),inGracePeriod:subscriptionState.includes('IN_GRACE_PERIOD'),revoked:subscriptionState.includes('EXPIRED')||subscriptionState.includes('REVOKED'),refunded:subscriptionState.includes('REVOKED'),cancelReason};
 }
}
