function New-AI5Result {
  param([string]$TaskId,[string]$Agent,[string]$Status='SUCCESS',[string]$Summary='')
  [ordered]@{task_id=$TaskId;ai=$Agent;agent=$Agent;result=$Summary;summary=$Summary;verdict=$(if($Status-in@('SUCCESS','PASS','success')){'PASS'}else{'FAIL'});status=$Status;evidence=@();acceptance_outcomes=@();files_changed=@();commit='';tests=@();qa=@();blockers=@();resource_status='UNKNOWN';approval_required=$false;recommended_next_action='VALIDATE';findings=@();changes=@();artifacts=@();risks=@();next_action='VALIDATE';needs_human=$false;human_reason=$null}
}
function Initialize-AI5TaskV6Fields {
  param($Task,$Body,$Route)
  $hasRepositoryContext=([bool]$Body.repositoryPath-and[bool]$Body.branch-and[bool]$Body.sourceCommit)
  $selectedWriter=if($Body.writer){[string]$Body.writer}elseif($hasRepositoryContext){[string]$Route.writer}else{'NONE'}
  $values=[ordered]@{assigned_ai=$Route.primary;support_ai=@($Route.secondary);writer=$selectedWriter;operation=$(if($Body.operation){[string]$Body.operation}elseif($selectedWriter-eq'NONE'){'read_only'}else{'code_change'});repository_path=$(if($Body.repositoryPath){[string]$Body.repositoryPath}else{''});branch=$(if($Body.branch){[string]$Body.branch}else{''});source_commit=$(if($Body.sourceCommit){[string]$Body.sourceCommit}else{''});expected_output=$(if($Body.expectedOutput){Protect-AI5Text([string]$Body.expectedOutput)}else{'担当結果・証拠・QA・次工程'});acceptance_criteria=@($(if($Body.acceptanceCriteria){@(Protect-AI5Object $Body.acceptanceCriteria)}else{@('結果schemaを満たす','証拠を返す','独立監査を通す')}));retry_count=0;resource_status=[string]$Route.resourceStatus[$Route.primary];payload_hash=Get-AI5PayloadHash([string]$Body.message);repository_lock=$null;independent_audit=[ordered]@{status='PENDING';ai='';evidence=@()};agent_results=@()}
  foreach($entry in $values.GetEnumerator()){$Task|Add-Member -NotePropertyName $entry.Key -NotePropertyValue $entry.Value -Force};$Task
}
function Enter-AI5TaskWriterLock {param($Task,[string]$RuntimeRoot);if($Task.writer-eq'NONE'){return $true};if(!$Task.repository_path-or!$Task.branch-or!$Task.source_commit){throw'writer_requires_repository_branch_source_commit'};if($Task.repository_lock){return $true};$Task.repository_lock=Enter-AI5RepositoryLock $RuntimeRoot $Task.task_id $Task.repository_path $Task.branch $Task.writer $Task.source_commit;Save-AI5Task $Task;$true}
function Exit-AI5TaskWriterLock {param($Task);if($Task.repository_lock){Exit-AI5RepositoryLock $Task.repository_lock $Task.task_id;$Task.repository_lock=$null;Save-AI5Task $Task}}
function New-AI5Children {
  param($Task,$Route)
  $reviewer=if($Route.primary-eq'claude'){'manus'}else{'claude'}
  $steps=@([ordered]@{title='GitHub正本確認';agent='zero';phase='source_of_truth'},[ordered]@{title='施工';agent=$Route.primary;phase='execution'},[ordered]@{title='独立検査';agent=$reviewer;phase='independent_audit'},[ordered]@{title='Zero統合判定';agent='zero';phase='decision'})
  if($Route.primary-eq'gemini'){$steps+=,[ordered]@{title='調査結果検証';agent='manus';phase='independent_audit'}}
  $i=0;@($steps|ForEach-Object{$i++;[ordered]@{task_id=('{0}-{1:D2}'-f$Task.task_id,$i);parent_task_id=$Task.task_id;title=$_.title;assigned_agent=$_.agent;phase=$_.phase;status='RECEIVED';created_at=$Task.created_at;updated_at=$Task.created_at;result=$null}})
}
function ConvertTo-AI5LegacyStatus([string]$Status){@{RECEIVED='queued';PLANNING='planning';ROUTING='planning';RUNNING='running';VALIDATING='reviewing';RETRYING='running';BLOCKED='blocked';WAITING_APPROVAL='waiting_approval';COMPLETED='completed';FAILED='failed';ESCALATED='failed';CANCELLED='cancelled'}[$Status]}
function Set-AI5TaskStatus {param($Task,[string]$Status,[string]$Label);$Task.canonical_status=$Status;$Task.status=ConvertTo-AI5LegacyStatus $Status;$Task.updated_at=[DateTime]::UtcNow.ToString('o');$Task.updatedAt=$Task.updated_at;$Task.timeline+=,[ordered]@{status=$Status;label=$Label;at=$Task.updated_at};Save-AI5Task $Task;if($Status-in@('COMPLETED','FAILED','ESCALATED','CANCELLED')-and$script:AI5EvidenceAppRoot){$Task.evidence_export=Export-AI5TaskEvidence -AppRoot $script:AI5EvidenceAppRoot -Task $Task -Result $Task.result -Audit $Task.validation;Save-AI5Task $Task}}
function Test-AI5Completion {
  param($Task)
  $tests=@($Task.result.tests);$qa=@($Task.result.qa);$evidence=@($Task.result.evidence);$outcomes=@($Task.result.acceptance_outcomes);$hasFailure=@($tests+$qa|Where-Object{$_-match'(?i)fail|error|ng|\b0\s*/'});$explicitPass=($tests.Count-gt0-and$qa.Count-gt0-and@($tests+$qa|Where-Object{$_-notmatch'(?i)\bpass(?:ed)?\b|成功|合格'}).Count-eq0);$hasProof=($evidence.Count-gt0-and@($evidence|Where-Object{$_-notmatch'^(?i)(https://|path:|commit:)'}).Count-eq0);$criteria=@($Task.acceptance_criteria);$outcomesOk=($criteria.Count-gt0-and$outcomes.Count-eq$criteria.Count-and@($outcomes|Where-Object{$_.status-ne'PASS'-or![string]$_.criterion-or![string]$_.evidence}).Count-eq0);$auditOk=($Task.independent_audit.status-eq'PASS'-and$Task.independent_audit.ai-ne$Task.result.ai)-or$Task.route.workType-in@('conversation','control')
  $checks=[ordered]@{result_schema=($null-ne$Task.result);tests=($tests.Count-gt0);qa=($qa.Count-gt0);explicit_pass=$explicitPass;evidence=$hasProof;no_reported_failure=($hasFailure.Count-eq0);acceptance_criteria=$outcomesOk;independent_audit=$auditOk}
  [ordered]@{passed=($Task.result.verdict-eq'PASS'-and!($checks.Values-contains$false));checks=$checks;checked_at=[DateTime]::UtcNow.ToString('o')}
}
function Get-AI5FailureAction {param($Task,[string]$ErrorType);if($Task.retry_count-ge$Task.max_attempts){return 'ESCALATED'};if($ErrorType-in@('authentication_failed','approval_required')){return 'WAIT_APPROVAL'};if($ErrorType-in@('unknown_cause','complex_bug','security_review','web_verification','browser_required','manus_timeout')){return 'REROUTE_CLAUDE'};if($ErrorType-in@('latest_spec','research_required')){return 'REROUTE_GEMINI'};if($Task.assigned_ai-eq'codex'){return 'REROUTE_CLAUDE'};if($Task.assigned_ai-eq'gemini'){return 'REROUTE_MANUS'};'RETRY_ASSIGNED'}
function ConvertTo-AI5ReturnResult {
  param($Body,$Task)
  $required=@('task_id','ai','result','verdict','evidence','acceptance_outcomes','files_changed','commit','tests','qa','blockers','resource_status','approval_required','recommended_next_action');foreach($name in $required){if($null-eq$Body.PSObject.Properties[$name]){throw "result_schema_missing_$name"}}
  $ai=[string]$Body.ai;if($ai-notin@('manus','claude','gemini','codex')){throw 'invalid_result_ai'};if($ai-ne[string]$Task.assigned_ai){throw 'assigned_ai_mismatch'};if([string]$Body.task_id-ne[string]$Task.task_id){throw 'task_id_mismatch'};foreach($name in @('evidence','acceptance_outcomes','files_changed','tests','qa','blockers')){if($Body.$name-is[string]-or$Body.$name-isnot[Collections.IEnumerable]){throw "result_schema_invalid_$name"}};foreach($outcome in @($Body.acceptance_outcomes)){if(!$outcome.criterion-or$outcome.status-ne'PASS'-or!$outcome.evidence){throw 'invalid_acceptance_outcome'}};$verdict=([string]$Body.verdict).ToUpperInvariant();if($verdict-notin@('PASS','FAIL','BLOCKED','PARTIAL')){throw 'invalid_result_verdict'};$resource=([string]$Body.resource_status).ToUpperInvariant();if($resource-notin@('AVAILABLE','LIMITED','EXHAUSTED','TIMEOUT','UNKNOWN')){throw 'invalid_resource_status'}
  $safe=Protect-AI5Object $Body;[ordered]@{task_id=$Task.task_id;ai=$ai;agent=$ai;result=[string]$safe.result;summary=[string]$safe.result;verdict=$verdict;status=$(if($verdict-eq'PASS'){'SUCCESS'}elseif($verdict-eq'PARTIAL'){'PARTIAL'}else{'FAILED'});evidence=@($safe.evidence);acceptance_outcomes=@($safe.acceptance_outcomes);files_changed=@($safe.files_changed);commit=[string]$safe.commit;tests=@($safe.tests);qa=@($safe.qa);blockers=@($safe.blockers);resource_status=$resource;approval_required=[bool]$safe.approval_required;recommended_next_action=[string]$safe.recommended_next_action;findings=@();changes=@($safe.files_changed);artifacts=@($safe.evidence);risks=@($safe.blockers);next_action=[string]$safe.recommended_next_action;needs_human=[bool]$safe.approval_required;human_reason=$(if($safe.approval_required){(@($safe.blockers)-join'; ')}else{$null})}
}
function Receive-AI5ExternalResult {
  param($Task,$Body)
  $result=ConvertTo-AI5ReturnResult $Body $Task;$Task.agent_results+=,$result;$Task.result=$result;if($result.ai-in@('manus','gemini')){Complete-AI5ExternalTask $Task.task_id $result.ai}
  if($result.approval_required){Exit-AI5TaskWriterLock $Task;$Task.requiresApproval=$true;$Task.approval=[ordered]@{type='external_result';summary=(@($result.blockers)-join'; ');status='pending';zero_review=[ordered]@{verdict='APPROVAL_OK';reason='AI result requires Teppei decision';risks=@($result.blockers);checks=@('Zero Return schema accepted')}};Set-AI5TaskStatus $Task 'WAITING_APPROVAL' '本人承認待ち';return $Task}
  if($result.verdict-eq'PASS'){
    Set-AI5TaskStatus $Task 'VALIDATING' 'Zeroが結果を回収・独立監査開始';$audit=Invoke-AI5ClaudeAdapter $Task;$Task.agent_results+=,$audit;$Task.independent_audit=[ordered]@{status=$(if($audit.verdict-eq'PASS'){'PASS'}else{'FAIL'});ai='claude';evidence=@($audit.evidence);summary=$audit.summary}
    $Task.validation=Test-AI5Completion $Task;Exit-AI5TaskWriterLock $Task;if($Task.validation.passed){Set-AI5TaskStatus $Task 'COMPLETED' 'Zero統合判定 PASS'}else{Set-AI5TaskStatus $Task 'BLOCKED' '独立監査または受入証拠不足'};return $Task
  }
  Exit-AI5TaskWriterLock $Task;$Task.retry_count++;$Task.attempt=[Math]::Max($Task.attempt,$Task.retry_count);$errorType=if($result.resource_status-eq'TIMEOUT'){"$($result.ai)_timeout"}elseif($result.verdict-eq'BLOCKED'){'unknown_cause'}else{'task_failed'};$action=Get-AI5FailureAction $Task $errorType
  switch($action){'WAIT_APPROVAL'{$Task.requiresApproval=$true;Set-AI5TaskStatus $Task 'WAITING_APPROVAL' '本人操作待ち'}'REROUTE_CLAUDE'{$Task.assignedPrimary='claude';$Task.assigned_ai='claude';$Task.assigned_agent='claude';$Task.writer=$(if($Task.writer-eq'NONE'){'NONE'}else{'claude'});Set-AI5TaskStatus $Task 'RETRYING' 'ClaudeへFallback';Dispatch-Task $Task}'REROUTE_MANUS'{$Task.assignedPrimary='manus';$Task.assigned_ai='manus';$Task.assigned_agent='manus';Set-AI5TaskStatus $Task 'RETRYING' 'ManusへFallback';Dispatch-Task $Task}'REROUTE_GEMINI'{$Task.assignedPrimary='gemini';$Task.assigned_ai='gemini';$Task.assigned_agent='gemini';$Task.writer='NONE';Set-AI5TaskStatus $Task 'RETRYING' 'GeminiへFallback';Dispatch-Task $Task}'RETRY_ASSIGNED'{Set-AI5TaskStatus $Task 'RETRYING' '同一AIへ再施工';Dispatch-Task $Task}default{Set-AI5TaskStatus $Task 'ESCALATED' 'retry上限・Zero判断待ち'}};$Task
}
