import test from'node:test';import assert from'node:assert/strict';
import{createService,decideEntitlement,ENTITLEMENT,FakeVerifier,MemoryLedger}from'../src/core.js';
const config={packageName:'app.daimon',productId:'daimon_monthly',hmacKey:'test-hmac',timeoutMs:25,maxRetries:1};
const body={packageName:config.packageName,productId:config.productId,purchaseToken:'token-a'};
test('state machine covers lifecycle',()=>{const future=2000,now=1000,b={productId:'p',packageName:'x',expiryTimeMillis:future,acknowledged:true};assert.equal(decideEntitlement(b,now),ENTITLEMENT.ACTIVE);assert.equal(decideEntitlement({...b,acknowledged:false},now),ENTITLEMENT.PENDING);assert.equal(decideEntitlement({...b,paymentState:'PENDING'},now),ENTITLEMENT.PENDING);assert.equal(decideEntitlement({...b,expiryTimeMillis:900},now),ENTITLEMENT.INACTIVE);assert.equal(decideEntitlement({...b,refunded:true},now),ENTITLEMENT.INACTIVE);assert.equal(decideEntitlement({...b,cancelReason:'USER'},now),ENTITLEMENT.ACTIVE);});
test('valid purchase grants without token logging',async()=>{const verifier=new FakeVerifier(new Map([['token-a',{expiryTimeMillis:2000,acknowledged:true}]])),events=[],service=createService({config,verifier,ledger:new MemoryLedger(),audit:e=>events.push(e),now:()=>1000}),result=await service(body);assert.equal(result.entitlement,'ACTIVE');assert.doesNotMatch(JSON.stringify(events),/token-a/);});
test('same token is idempotent',async()=>{const verifier=new FakeVerifier(new Map([['token-a',{expiryTimeMillis:2000,acknowledged:true}]])),service=createService({config,verifier,ledger:new MemoryLedger(),audit:()=>{},now:()=>1000});await service(body);assert.equal((await service(body)).idempotent,true);assert.equal(verifier.calls,1);});
test('identity mismatch and unknown token fail closed',async()=>{const service=createService({config,verifier:new FakeVerifier(),ledger:new MemoryLedger(),audit:()=>{}});await assert.rejects(()=>service({...body,productId:'evil'}),/identity mismatch/);await assert.rejects(()=>service(body),/not found/);});
test('timeout retries then fails',async()=>{let calls=0;const service=createService({config,verifier:{verify:async()=>{calls++;await new Promise(r=>setTimeout(r,60));}},ledger:new MemoryLedger(),audit:()=>{}});await assert.rejects(()=>service(body),/timeout/);assert.equal(calls,2);});
