function Initialize-AI5ApprovalRouting {
    param([string]$ServerRoot)
    $script:AI5ApprovalDecisionRoot = Join-Path $ServerRoot 'runtime\approval-decisions'
    New-Item -ItemType Directory -Force $script:AI5ApprovalDecisionRoot | Out-Null
}
function ConvertTo-AI5ApprovalSignal { param([string]$Signal) $n=$Signal.Trim().ToUpperInvariant()-replace'[^A-Z0-9]+','_';if($n-in@('APPROVAL_REQUIRED','OWNER_CONFIRMATION','PERMISSION_REQUIRED','PUBLICATION_CONFIRM','MONEY_GATE','OWNER_APPROVAL_REQUIRED')){return 'AI5_HUB_APPROVAL_TASK'};if($n-in@('OWNER_ACTION_REQUIRED','OTP_REQUIRED','CAPTCHA_REQUIRED','KYC_REQUIRED','IDENTITY_VERIFICATION_REQUIRED','BIOMETRIC_REQUIRED')){return 'OWNER_ACTION_REQUIRED'};$n }
function Get-AI5ApprovalPriority { param($Policy) if($Policy.money-or$Policy.type-in@('money_or_contract','owner_only','production')){return 'P0'};if($Policy.type-in@('hub_approval','external_publish','external_send','publication')){return 'P1'};'P2' }
function New-AI5HubApprovalPayload {
 param($Task,$Policy,$Context);$cost=if($Context.values.amount){[string]$Context.values.amount}elseif($Policy.money){'UNVERIFIED'}else{'¥0'}
 [ordered]@{schema_version='2026-09-01.1';type='AI5_HUB_APPROVAL_TASK';task_id=[string]$Task.taskId;project=[string]$Task.project_id;action=[string]$Context.values.operationContent;why=[string]$Context.values.specificReason;exact_scope=[ordered]@{product=[string]$Task.product;channel=[string]$Task.channel;account_service=[string]$Context.values.accountService;objective=[string]$Task.objective};visibility=$(if(([string]$Context.values.externalImpact)-match'(?i)public|公開'){'PUBLIC'}else{'PRIVATE'});cost=$cost;reversible=$(if($null-ne$Task.reversible){[bool]$Task.reversible}else{[bool]$Policy.reversible});risk=$(if([int]$Policy.level-ge2){'HIGH'}elseif([int]$Policy.level-eq1){'MEDIUM'}else{'LOW'});what_changes=[string]$Context.values.externalImpact;what_does_not_change=@($Task.whatDoesNotChange);priority=(Get-AI5ApprovalPriority $Policy);owner_action_required=[bool]$Policy.ownerOperationRequired;owner_action=$(if($Policy.ownerOperationRequired){[string]$Task.ownerAction}else{$null});after_approval=[string]$Context.values.afterApproval;approve_button='APPROVE';reject_button='REJECT';expires_at=$(if($Task.expiresAt){[string]$Task.expiresAt}else{$null});scope_hash=[string]$Policy.scopeHash;idempotency_key=[string]$Task.idempotencyKey;global_state='EXECUTING';blocked_scope='THIS_TASK_ONLY';created_at=[DateTimeOffset]::Now.ToString('o')}
}
function Save-AI5ApprovalDecision { param($Task,[ValidateSet('APPROVE','REJECT')]$Decision,[string]$Actor,[string]$ReceiptId) $r=[ordered]@{schema_version='2026-09-01.1';task_id=[string]$Task.taskId;decision=$Decision;timestamp=[DateTimeOffset]::Now.ToString('o');scope=$Task.approvalTask.exact_scope;owner_action=$Task.approvalTask.owner_action;receipt=$ReceiptId;scope_hash=[string]$Task.approval.scopeHash;idempotency_key=[string]$Task.idempotencyKey;actor=$Actor;result_bus_state='DECISION_READY';auto_resume=($Decision-eq'APPROVE')};$p=Join-Path $script:AI5ApprovalDecisionRoot (([string]$Task.taskId-replace'[^A-Za-z0-9_.-]','_')+'.json');$t="$p.tmp";[IO.File]::WriteAllText($t,($r|ConvertTo-Json -Depth 12),[Text.UTF8Encoding]::new($false));Move-Item -LiteralPath $t -Destination $p -Force;$r }
function Get-AI5NextUnblockedTask { param([object[]]$Tasks,[string]$ExcludeTaskId='') @($Tasks|Where-Object{$_.taskId-ne$ExcludeTaskId-and$_.status-in@('queued','RECEIVED','READY')-and!$_.queue_reason-and!$_.blocked_by-and!$_.requiresApproval}|Sort-Object createdAt|Select-Object -First 1) }
function Test-AI5ApprovalWatchdog { param([object[]]$Tasks,[DateTimeOffset]$Now=[DateTimeOffset]::Now) $j=[TimeZoneInfo]::ConvertTime($Now,[TimeZoneInfo]::FindSystemTimeZoneById('Tokyo Standard Time'));$w=@($Tasks|Where-Object{$_.status-eq'waiting_approval'}).Count;$a=@($Tasks|Where-Object{$_.status-in@('planning','running','reviewing','retrying')}).Count;$b=$j.Hour-ge8-and$j.Hour-lt18;$n=Get-AI5NextUnblockedTask $Tasks;[ordered]@{stall=($b-and$w-gt0-and$a-eq0);business_window=$b;waiting_approval_count=$w;active_task_count=$a;action=$(if($b-and$w-gt0-and$a-eq0-and$n){'AUTO_CLAIM_NEXT_UNBLOCKED_TASK'}else{'NONE'});next_task_id=$(if($n){$n.taskId}else{$null});global_state='EXECUTING'} }
