function Initialize-AI5GitHubResultLoop([string]$ServerRoot,[string]$BusRoot='') {
  $script:GHBusRoot=if($BusRoot){[IO.Path]::GetFullPath($BusRoot)}else{Join-Path $ServerRoot 'data\github-result-loop'}
  $script:GHTasks=Join-Path $script:GHBusRoot 'tasks';$script:GHResults=Join-Path $script:GHBusRoot 'results';$script:GHLocks=Join-Path $script:GHBusRoot 'locks';$script:GHInbox=Join-Path $script:GHBusRoot 'inbox';$script:GHReceipts=Join-Path $script:GHBusRoot 'receipts';$script:GHArchive=Join-Path $script:GHBusRoot 'archive'
  @($script:GHBusRoot,$script:GHTasks,$script:GHResults,$script:GHLocks,$script:GHInbox,$script:GHReceipts,$script:GHArchive)|ForEach-Object{New-Item -ItemType Directory -Force $_|Out-Null}
  $configPath=Join-Path $script:GHBusRoot 'config.json';if(!(Test-Path $configPath)){Write-GHBusJson ([ordered]@{schema_version=1;mode='GITHUB_DEGRADED';remote_enabled=$false;remote_visibility='UNVERIFIED';browser_state='DEGRADED';updated_at=Get-GHBusNow}) $configPath}
}
function Get-GHBusNow{[DateTimeOffset]::Now.ToString('o')}
function Get-GHBusSafeId([string]$Value){if($Value-notmatch'^[A-Za-z0-9][A-Za-z0-9._-]{1,119}$'){throw'invalid_bus_id'};$Value}
function Read-GHBusJson([string]$Path){[IO.File]::ReadAllText($Path,[Text.UTF8Encoding]::new($false))|ConvertFrom-Json}
function Write-GHBusJson($Value,[string]$Path){$tmp="$Path.tmp";[IO.File]::WriteAllText($tmp,($Value|ConvertTo-Json -Depth 15),[Text.UTF8Encoding]::new($false));Move-Item -LiteralPath $tmp -Destination $Path -Force}
function Test-GHBusSecret([string]$Text){$Text-match'(?i)(password|passwd|api[_-]?key|oauth[_-]?secret|access[_-]?token|refresh[_-]?token|2fa\s*code|秘密鍵)\s*[:=]\s*\S+'}
function Get-AI5GitHubBusConfig{Read-GHBusJson (Join-Path $script:GHBusRoot 'config.json')}
function Set-AI5GitHubBusMode([string]$Mode,[string]$BrowserState='DEGRADED') {if($Mode-notin@('NORMAL','GITHUB_DEGRADED')){throw'invalid_bus_mode'};$c=Get-AI5GitHubBusConfig;$c.mode=$Mode;$c.browser_state=$BrowserState;$c.updated_at=Get-GHBusNow;Write-GHBusJson $c (Join-Path $script:GHBusRoot 'config.json');$c}
function New-AI5GitHubBusTask($Body) {
  $id=Get-GHBusSafeId ([string]$Body.task_id);$text=([string]$Body.objective)+' '+([string]$Body.instructions);if(Test-GHBusSecret $text){throw'secret_in_task_rejected'}
  $path=Join-Path $script:GHTasks ($id+'.json');if(Test-Path $path){return (Read-GHBusJson $path)};$now=Get-GHBusNow
  $task=[ordered]@{schema_version=1;task_id=$id;project_id=[string]$Body.project_id;product_id=[string]$Body.product_id;parent_task_id=[string]$Body.parent_task_id;created_by='zero';assigned_ai=([string]$Body.assigned_ai).ToLowerInvariant();support_ai=@($Body.support_ai);writer=([string]$Body.writer).ToLowerInvariant();priority=$(if($Body.priority){[string]$Body.priority}else{'NORMAL'});objective=[string]$Body.objective;instructions=[string]$Body.instructions;acceptance_criteria=@($Body.acceptance_criteria);source_repository=[string]$Body.source_repository;source_branch=[string]$Body.source_branch;source_commit=[string]$Body.source_commit;status=$(if($Body.approval_required){'APPROVAL_REQUIRED'}else{'QUEUED'});retry_count=[int]$Body.retry_count;max_retry=$(if($null-ne$Body.max_retry){[int]$Body.max_retry}else{3});loop_state=$(if($Body.loop_state){$Body.loop_state}else{[ordered]@{decision='PLAN';attemptCount=0;sameFailureCount=0;redispatchCount=0;dailyExecutionCount=0}});approval_required=[bool]$Body.approval_required;resource_status=$(if($Body.resource_status){[string]$Body.resource_status}else{'UNKNOWN'});created_at=$now;updated_at=$now}
  if($task.assigned_ai-notin@('codex','claude','gemini','manus','notebooklm')){throw'invalid_assigned_ai'};if(!$task.objective){throw'objective_required'};Write-GHBusJson $task $path;$task
}
function Get-AI5GitHubBusTasks([string]$AssignedAI=''){Get-ChildItem $script:GHTasks -Filter '*.json' -ErrorAction SilentlyContinue|ForEach-Object{Read-GHBusJson $_.FullName}|Where-Object{!$AssignedAI-or$_.assigned_ai-eq$AssignedAI}|Sort-Object created_at}
function Claim-AI5GitHubBusTask([string]$TaskId,[string]$AI,[int]$TtlMinutes=30) {
  $id=Get-GHBusSafeId $TaskId;$taskPath=Join-Path $script:GHTasks ($id+'.json');if(!(Test-Path $taskPath)){throw'task_not_found'};$task=Read-GHBusJson $taskPath;if($task.assigned_ai-ne$AI){throw'wrong_ai_queue'};if($task.status-ne'QUEUED'){throw'task_not_claimable'}
  $lockPath=Join-Path $script:GHLocks ($id+'.json');if(Test-Path $lockPath){$old=Read-GHBusJson $lockPath;if([DateTimeOffset]::Parse($old.expires_at)-gt[DateTimeOffset]::Now){throw'single_writer_locked'};if($old.owner-ne$AI){throw'stale_lock_owner_unverified'};Remove-Item -LiteralPath $lockPath -Force}
  $lock=[ordered]@{project_id=$task.project_id;repository=$task.source_repository;branch=$task.source_branch;writer=$task.writer;owner=$AI;task_id=$id;locked_at=Get-GHBusNow;heartbeat_at=Get-GHBusNow;expires_at=[DateTimeOffset]::Now.AddMinutes($TtlMinutes).ToString('o')};Write-GHBusJson $lock $lockPath;$task.status='CLAIMED';$task.updated_at=Get-GHBusNow;Write-GHBusJson $task $taskPath;$lock
}
function Update-AI5GitHubBusHeartbeat([string]$TaskId,[string]$AI,[int]$TtlMinutes=30){$path=Join-Path $script:GHLocks ((Get-GHBusSafeId $TaskId)+'.json');if(!(Test-Path $path)){throw'lock_not_found'};$lock=Read-GHBusJson $path;if($lock.owner-ne$AI){throw'lock_owner_mismatch'};$lock.heartbeat_at=Get-GHBusNow;$lock.expires_at=[DateTimeOffset]::Now.AddMinutes($TtlMinutes).ToString('o');Write-GHBusJson $lock $path;$lock}
function Release-AI5GitHubBusLock([string]$TaskId,[string]$AI){$path=Join-Path $script:GHLocks ((Get-GHBusSafeId $TaskId)+'.json');if(Test-Path $path){$lock=Read-GHBusJson $path;if($lock.owner-ne$AI){throw'lock_owner_mismatch'};Remove-Item -LiteralPath $path -Force};$true}
function New-AI5GitHubBusResult($Body) {
  $taskId=Get-GHBusSafeId ([string]$Body.task_id);$version=if($Body.result_version){[int]$Body.result_version}else{1};$resultId="$taskId-v$version";$path=Join-Path $script:GHResults ($resultId+'.json');if(Test-Path $path){return [ordered]@{duplicate=$true;result=Read-GHBusJson $path}}
  if(Test-GHBusSecret (([string]$Body.summary)+' '+(@($Body.evidence)-join' '))){throw'secret_in_result_rejected'};$now=Get-GHBusNow;$result=[ordered]@{schema_version=1;result_id=$resultId;result_version=$version;task_id=$taskId;taskId=$taskId;ai=([string]$Body.ai).ToLowerInvariant();agent=([string]$Body.ai).ToLowerInvariant();status=$(if($Body.status){[string]$Body.status}else{'COMPLETED'});result=$(if($Body.result){[string]$Body.result}else{'PASS'});summary=[string]$Body.summary;actions=@($Body.actions);evidence=@($Body.evidence);tests=@($Body.tests);changedFiles=@($Body.files_changed);files_changed=@($Body.files_changed);issues=@($Body.blockers);recommendation=[string]$Body.recommended_next_action;needsRework=([string]$Body.result-in@('FAIL','BLOCKED'));needsApproval=[bool]$Body.approval_required;repository=[string]$Body.repository;branch=[string]$Body.branch;commit=[string]$Body.commit;qa=@($Body.qa);audit=[string]$Body.audit;blockers=@($Body.blockers);approval_required=[bool]$Body.approval_required;recommended_next_action=[string]$Body.recommended_next_action;resource_status=$(if($Body.resource_status){[string]$Body.resource_status}else{'UNKNOWN'});finished_at=$(if($Body.finished_at){[string]$Body.finished_at}else{$now})};Write-GHBusJson $result $path
  $taskPath=Join-Path $script:GHTasks ($taskId+'.json');if(Test-Path $taskPath){$task=Read-GHBusJson $taskPath;$task.status=$(if($result.approval_required){'APPROVAL_REQUIRED'}elseif($result.result-eq'PASS'){'COMPLETED'}elseif($result.result-eq'BLOCKED'){'BLOCKED'}else{'FAILED'});$task.updated_at=$now;Write-GHBusJson $task $taskPath;Release-AI5GitHubBusLock $taskId $result.ai|Out-Null};[ordered]@{duplicate=$false;result=$result}
}
function Get-AI5GitHubFallback([string]$AI,[string]$Reason,[string]$Objective=''){if($Reason-match'BROWSER'-or$Objective-match'(?i)browser|web|ブラウザ'){if($AI-eq'manus'){return 'claude'};return 'manus'};@{codex='claude';claude='codex';gemini='manus';manus='claude';notebooklm='gemini'}[$AI]}
function Get-AI5GitHubNextAI([string]$Action){if($Action-match'(?i)claude|監査|audit|review'){return 'claude'};if($Action-match'(?i)manus|browser|web|qa'){return 'manus'};if($Action-match'(?i)gemini|research|調査'){return 'gemini'};if($Action-match'(?i)notebook|資料'){return 'notebooklm'};'codex'}
function Get-AI5GitHubResultDecision($Task,$Result){if($Result.approval_required-or$Task.approval_required){return [ordered]@{decision='APPROVAL_REQUIRED';next_ai='';reason='human_gate'}};if($Result.result-eq'PASS'){return [ordered]@{decision='PASS';next_ai='';reason='acceptance_result_pass'}};if($Result.result-eq'BLOCKED'-or@($Result.blockers)-contains'BLOCKED_BROWSER'){$next=Get-AI5GitHubFallback $Result.ai (@($Result.blockers)-join',') $Task.objective;return [ordered]@{decision='FALLBACK';next_ai=$next;reason='blocked_fallback'}};if($Task.retry_count-lt$Task.max_retry){return [ordered]@{decision='RETRY';next_ai=$Task.assigned_ai;reason='repairable_failure'}};[ordered]@{decision='ESCALATED';next_ai='';reason='max_retry'}}
function Invoke-AI5GitHubResultCollector {
  $handled=0;$created=0;foreach($file in Get-ChildItem $script:GHResults -Filter '*.json' -ErrorAction SilentlyContinue|Sort-Object LastWriteTime){$result=Read-GHBusJson $file.FullName;$receipt=Join-Path $script:GHReceipts ($result.result_id+'.json');if(Test-Path $receipt){continue};$taskPath=Join-Path $script:GHTasks ($result.task_id+'.json');if(!(Test-Path $taskPath)){continue};$task=Read-GHBusJson $taskPath;$decision=Get-AI5GitHubResultDecision $task $result;$inbox=[ordered]@{inbox_id=$result.result_id;unread=$true;ai=$result.ai;project_id=$task.project_id;product_id=$task.product_id;task_id=$task.task_id;result=$result.result;decision=$decision.decision;blockers=@($result.blockers);evidence=@($result.evidence);commit=$result.commit;approval_required=($decision.decision-eq'APPROVAL_REQUIRED');next_action=$result.recommended_next_action;created_at=Get-GHBusNow};Write-GHBusJson $inbox (Join-Path $script:GHInbox ($result.result_id+'.json'))
    $next=$null;$continueAction=$decision.decision-eq'PASS'-and$result.recommended_next_action-and$result.recommended_next_action-notmatch'(?i)^(complete|完了|なし|none)$';if($decision.decision-in@('RETRY','FALLBACK')-or$continueAction){$nextAI=if($continueAction){Get-AI5GitHubNextAI $result.recommended_next_action}else{$decision.next_ai};$suffix=if($decision.decision-eq'RETRY'){"retry-$([int]$task.retry_count+1)"}elseif($decision.decision-eq'FALLBACK'){"fallback-$nextAI"}else{"next-$nextAI"};$nextId=Get-GHBusSafeId ($task.task_id+'-'+$suffix);$next=New-AI5GitHubBusTask ([pscustomobject]@{task_id=$nextId;project_id=$task.project_id;product_id=$task.product_id;parent_task_id=$task.task_id;assigned_ai=$nextAI;support_ai=@();writer=$nextAI;priority=$task.priority;objective=$(if($continueAction){$result.recommended_next_action}else{$task.objective});instructions="Zero redispatch: $(if($continueAction){'PASS_CONTINUE'}else{$decision.reason}). Previous result: $($result.summary)";acceptance_criteria=$task.acceptance_criteria;source_repository=$task.source_repository;source_branch=$task.source_branch;source_commit=$task.source_commit;retry_count=$(if($decision.decision-eq'RETRY'){[int]$task.retry_count+1}else{0});max_retry=$task.max_retry;approval_required=$false});$created++}
    Write-GHBusJson ([ordered]@{result_id=$result.result_id;task_id=$task.task_id;decision=$decision;next_task_id=$next.task_id;processed_at=Get-GHBusNow}) $receipt;$handled++}
  [ordered]@{processed=$handled;redispatched=$created;unread=@(Get-AI5ZeroInbox|Where-Object{$_.unread}).Count}
}
function Get-AI5ZeroInbox{Get-ChildItem $script:GHInbox -Filter '*.json' -ErrorAction SilentlyContinue|ForEach-Object{Read-GHBusJson $_.FullName}|Sort-Object created_at -Descending}
function Get-AI5GitHubBusLineMessages{Get-AI5ZeroInbox|ForEach-Object{[ordered]@{id=('github-'+$_.inbox_id);taskId=$_.task_id;agent=$_.ai;state=$_.decision;text="結果：$($_.result)`nZero判定：$($_.decision)$(if($_.next_action){"`n次：$($_.next_action)"})";kind='github_result';at=$_.created_at;meta=$_}}}
function Get-AI5GitHubBusProjectStatus([string]$ProjectId){$tasks=@(Get-AI5GitHubBusTasks|Where-Object{$_.project_id-eq$ProjectId});$inbox=@(Get-AI5ZeroInbox|Where-Object{$_.project_id-eq$ProjectId});[ordered]@{currentTask=($tasks|Where-Object{$_.status-in@('QUEUED','CLAIMED','RUNNING','REVIEW')}|Select-Object -Last 1).task_id;assignedAI=($tasks|Select-Object -Last 1).assigned_ai;writer=($tasks|Select-Object -Last 1).writer;queue=@($tasks|Where-Object{$_.status-eq'QUEUED'}).Count;running=@($tasks|Where-Object{$_.status-in@('CLAIMED','RUNNING','REVIEW')}).Count;latestResult=($inbox|Select-Object -First 1).result;blocker=(($inbox|Select-Object -First 1).blockers-join', ');approval=@($inbox|Where-Object{$_.approval_required}).Count;nextAction=($inbox|Select-Object -First 1).next_action;updatedAt=($inbox|Select-Object -First 1).created_at}}
function Get-AI5GitHubBusStatus{$c=Get-AI5GitHubBusConfig;[ordered]@{mode=$c.mode;browser=$c.browser_state;remoteEnabled=$c.remote_enabled;remoteVisibility=$c.remote_visibility;remoteRepository=$c.remote_repository;lastRemoteSync=$c.last_remote_sync;tasks=@(Get-AI5GitHubBusTasks).Count;results=@(Get-ChildItem $script:GHResults -Filter '*.json' -ErrorAction SilentlyContinue).Count;inbox=@(Get-AI5ZeroInbox).Count;unread=@(Get-AI5ZeroInbox|Where-Object{$_.unread}).Count;locks=@(Get-ChildItem $script:GHLocks -Filter '*.json' -ErrorAction SilentlyContinue).Count}}
function Test-AI5PrivateGitHubRemote([string]$RepoRoot){$url=& git -C $RepoRoot remote get-url origin 2>$null;if(!$url){return [ordered]@{allowed=$false;reason='remote_missing'}};$view=& gh repo view $url --json isPrivate,nameWithOwner 2>$null|ConvertFrom-Json;if(!$view-or!$view.isPrivate){return [ordered]@{allowed=$false;reason='private_remote_required';repository=$view.nameWithOwner}};[ordered]@{allowed=$true;reason='private_remote_verified';repository=$view.nameWithOwner}}
function Enable-AI5PrivateGitHubBusRemote([string]$RepoRoot){$check=Test-AI5PrivateGitHubRemote $RepoRoot;if(!$check.allowed){throw $check.reason};$c=Get-AI5GitHubBusConfig;$c.remote_enabled=$true;$c.remote_visibility='PRIVATE';$c|Add-Member remote_root ([IO.Path]::GetFullPath($RepoRoot)) -Force;$c|Add-Member remote_repository $check.repository -Force;$c.updated_at=Get-GHBusNow;Write-GHBusJson $c (Join-Path $script:GHBusRoot 'config.json');$c}
function Copy-GHBusJsonFiles([string]$Source,[string]$Destination){New-Item -ItemType Directory -Force $Destination|Out-Null;Get-ChildItem $Source -Filter '*.json' -File -ErrorAction SilentlyContinue|ForEach-Object{Copy-Item -LiteralPath $_.FullName -Destination (Join-Path $Destination $_.Name) -Force}}
function Test-GHBusRemoteContent([string]$RemoteRoot){$bad=@();Get-ChildItem (Join-Path $RemoteRoot 'bus') -Recurse -File -ErrorAction SilentlyContinue|ForEach-Object{$text=[IO.File]::ReadAllText($_.FullName,[Text.UTF8Encoding]::new($false));if((Test-GHBusSecret $text)-or($text-match'(?i)(ghp_|github_pat_|BEGIN (RSA|OPENSSH|EC) PRIVATE KEY|session[_-]?cookie|"?(password|passwd|api[_-]?key|oauth[_-]?secret|access[_-]?token|refresh[_-]?token|2fa[_ -]?code|秘密鍵)"?\s*[:=])')){$bad+=$_.FullName}};if($bad.Count){throw'remote_secret_scan_failed'};$true}
function Sync-AI5PrivateGitHubBusRemote([string]$Message='AI5 Result Bus sync'){
  $c=Get-AI5GitHubBusConfig;if(!$c.remote_enabled-or$c.remote_visibility-ne'PRIVATE'){throw'private_remote_not_enabled'};$check=Test-AI5PrivateGitHubRemote $c.remote_root;if(!$check.allowed){throw$check.reason}
  & git -C $c.remote_root pull --ff-only 2>$null|Out-Null;if($LASTEXITCODE-ne0-and(Test-Path (Join-Path $c.remote_root '.git\refs\heads\main'))){throw'git_pull_failed'}
  $bus=Join-Path $c.remote_root 'bus';Copy-GHBusJsonFiles $script:GHTasks (Join-Path $bus 'tasks');Copy-GHBusJsonFiles $script:GHResults (Join-Path $bus 'results');Copy-GHBusJsonFiles $script:GHInbox (Join-Path $bus 'decisions');Copy-GHBusJsonFiles $script:GHLocks (Join-Path $bus 'state\locks');Copy-GHBusJsonFiles $script:GHReceipts (Join-Path $bus 'state\receipts');Copy-GHBusJsonFiles $script:GHArchive (Join-Path $bus 'state\archive')
  Write-GHBusJson ([ordered]@{schema_version=1;mode=$c.mode;browser_state=$c.browser_state;repository=$check.repository;synchronized_at=Get-GHBusNow}) (Join-Path $bus 'state\loop-state.json');Test-GHBusRemoteContent $c.remote_root|Out-Null
  & git -C $c.remote_root add -- bus|Out-Null;if($LASTEXITCODE-ne0){throw'git_add_failed'};$dirty=& git -C $c.remote_root status --porcelain -- bus;if($dirty){& git -C $c.remote_root commit -m $Message|Out-Null;if($LASTEXITCODE-ne0){throw'git_commit_failed'};& git -C $c.remote_root push origin HEAD|Out-Null;if($LASTEXITCODE-ne0){throw'git_push_failed'}}
  $lastSync=Get-GHBusNow;$c|Add-Member last_remote_sync $lastSync -Force;$c.updated_at=$lastSync;Write-GHBusJson $c (Join-Path $script:GHBusRoot 'config.json');[ordered]@{synced=$true;repository=$check.repository;changed=[bool]$dirty;commit=(& git -C $c.remote_root rev-parse HEAD)}
}
function Restore-AI5PrivateGitHubBusRemote([string]$RepoRoot){
  $check=Test-AI5PrivateGitHubRemote $RepoRoot;if(!$check.allowed){throw$check.reason};& git -C $RepoRoot pull --ff-only|Out-Null;if($LASTEXITCODE-ne0){throw'git_pull_failed'};$bus=Join-Path $RepoRoot 'bus';Test-GHBusRemoteContent $RepoRoot|Out-Null
  Copy-GHBusJsonFiles (Join-Path $bus 'tasks') $script:GHTasks;Copy-GHBusJsonFiles (Join-Path $bus 'results') $script:GHResults;Copy-GHBusJsonFiles (Join-Path $bus 'decisions') $script:GHInbox;Copy-GHBusJsonFiles (Join-Path $bus 'state\locks') $script:GHLocks;Copy-GHBusJsonFiles (Join-Path $bus 'state\receipts') $script:GHReceipts;Copy-GHBusJsonFiles (Join-Path $bus 'state\archive') $script:GHArchive
  [ordered]@{restored=$true;repository=$check.repository;tasks=@(Get-AI5GitHubBusTasks).Count;results=@(Get-ChildItem $script:GHResults -Filter '*.json').Count;decisions=@(Get-AI5ZeroInbox).Count}
}
function Connect-AI5PrivateGitHubBusRemote([string]$RepoRoot=''){$c=Get-AI5GitHubBusConfig;$root=if($RepoRoot){$RepoRoot}elseif($c.remote_root){[string]$c.remote_root}else{''};if(!$root-or!(Test-Path $root)){return [ordered]@{connected=$false;reason='private_remote_root_unconfigured'}};$restored=Restore-AI5PrivateGitHubBusRemote $root;$enabled=Enable-AI5PrivateGitHubBusRemote $root;[ordered]@{connected=$true;repository=$enabled.remote_repository;restored=$restored}}
function Invoke-AI5GitHubBusAutoSync([string]$Message='AI5 automatic Result Bus sync'){$status=Get-AI5GitHubBusStatus;if(!$status.remoteEnabled){return [ordered]@{synced=$false;reason='remote_disabled'}};Sync-AI5PrivateGitHubBusRemote $Message}
function Publish-AI5LocalTaskToGitHubBus($Task){
  $id=Get-GHBusSafeId ([string]$Task.taskId);$existing=Get-AI5GitHubBusTasks|Where-Object{$_.task_id-eq$id}|Select-Object -First 1
  if(!$existing){$existing=New-AI5GitHubBusTask ([pscustomobject]@{task_id=$id;project_id=[string]$Task.project_id;parent_task_id=[string]$Task.parent_task_id;assigned_ai=$(if($Task.assignedPrimary){$Task.assignedPrimary}else{'codex'});support_ai=@($Task.assignedSecondary);writer=$(if($Task.assignedPrimary){$Task.assignedPrimary}else{'codex'});priority=[string]$Task.priority;objective=[string]$Task.objective;instructions=[string]$Task.message;acceptance_criteria=@($Task.route.doneWhen);source_repository=[string]$Task.projectContext.repository;source_branch=[string]$Task.projectContext.branch;retry_count=[int]$Task.loop_state.cycle;max_retry=$(if($Task.loop_state.maxCycles){[int]$Task.loop_state.maxCycles}else{3});loop_state=$Task.loop_state;approval_required=[bool]$Task.requiresApproval})}
  if(!$Task.result-or$Task.status-notin@('completed','failed','cancelled','waiting_approval')){return [ordered]@{published='TASK';task_id=$id}}
  $version=[Math]::Max(1,([int]$Task.attempt+1));$resultCode=if($Task.status-eq'completed'){'PASS'}elseif($Task.status-eq'waiting_approval'){'APPROVAL_REQUIRED'}elseif($Task.result.needs_human-or$Task.result.userActionRequired){'BLOCKED'}else{'FAIL'}
  $saved=New-AI5GitHubBusResult ([pscustomobject]@{task_id=$id;result_version=$version;ai=$(if($Task.result.agent){$Task.result.agent}else{$Task.assignedPrimary});status=([string]$Task.result.status).ToUpperInvariant();result=$resultCode;summary=[string]$Task.result.summary;actions=@($Task.result.actions)+@($Task.result.changes)+@($Task.result.details);evidence=@($Task.result.evidence)+@($Task.result.artifacts);files_changed=@($Task.result.changedFiles)+@($Task.result.filesChanged);repository=[string]$Task.projectContext.repository;branch=[string]$Task.projectContext.branch;commit=[string]$Task.result.commitId;tests=@($Task.result.tests);qa=@($Task.validation.checks.psobject.Properties.Name);audit=(@($Task.judgements|ForEach-Object{"$($_.agent):$($_.verdict)"})-join'; ');blockers=@($Task.result.issues)+@($Task.result.risks);approval_required=[bool]$Task.requiresApproval;recommended_next_action=$(if($Task.status-eq'completed'){'complete'}elseif($Task.loop_state.decision){[string]$Task.loop_state.decision}else{[string]$Task.result.next_action});resource_status='AVAILABLE'})
  $collected=Invoke-AI5GitHubResultCollector;[ordered]@{published=$(if($saved.duplicate){'DUPLICATE'}else{'RESULT'});task_id=$id;collector=$collected}
}
