function Initialize-AI5ProjectControl {
  param([string]$ServerRoot,[string]$AppRoot)
  $script:PCSourceRoot=Join-Path $AppRoot 'project-control';$script:PCWorkspaceRoot=Split-Path $AppRoot;$script:PCRoot=Join-Path $ServerRoot 'data\project-control';$script:PCProjects=Join-Path $script:PCRoot 'projects';$script:PCLocks=Join-Path $ServerRoot 'runtime\project-locks';$script:PCSchedulerPath=Join-Path $script:PCRoot 'scheduler-state.json';$script:PCLogRoot=Join-Path $ServerRoot 'logs\project-control'
  @($script:PCRoot,$script:PCProjects,$script:PCLocks,$script:PCLogRoot)|ForEach-Object{New-Item -ItemType Directory -Force $_|Out-Null}
  if(!(Test-Path (Join-Path $script:PCRoot 'registry.json'))){Copy-Item (Join-Path $script:PCSourceRoot 'registry.json') (Join-Path $script:PCRoot 'registry.json')}
  Get-ChildItem (Join-Path $script:PCSourceRoot 'projects') -Filter '*.json'|ForEach-Object{$to=Join-Path $script:PCProjects $_.Name;if(!(Test-Path $to)){Copy-Item $_.FullName $to}}
  if(!(Test-Path $script:PCSchedulerPath)){Write-PCJson @{status='STOPPED';lastScan='';nextScan='';activeProject='';lastResult='';intervalMinutes=60} $script:PCSchedulerPath}
  foreach($p in Get-AI5Projects){if('mode'-notin$p.autoExecution.psobject.Properties.Name){$p.autoExecution|Add-Member mode 'OFF'};$p.autoExecution.enabled=($p.autoExecution.mode-ne'OFF');if('sync'-notin$p.repository.psobject.Properties.Name){$p.repository|Add-Member sync ([pscustomobject]@{state='UNKNOWN';localHead='';remoteHead='';defaultHead='';ahead=0;behind=0;dirty=$false;checkedAt='';error=''})};if('execution'-notin$p.psobject.Properties.Name){$p|Add-Member execution ([pscustomobject]@{taskId='';lockId='';submittedAt='';resultRecoveredAt='';lastResult='';recoveryRequired=$false})}elseif('recoveryRequired'-notin$p.execution.psobject.Properties.Name){$p.execution|Add-Member recoveryRequired $false};if('autoRunsDate'-notin$p.executionPolicy.psobject.Properties.Name){$p.executionPolicy|Add-Member autoRunsDate ''; $p.executionPolicy|Add-Member autoRunsToday 0};Save-AI5Project $p}
}
function Get-PCNow{[DateTimeOffset]::Now.ToString('o')}
function Get-PCSafeId([string]$Id){if($Id-notmatch'^[a-z0-9][a-z0-9._-]{1,79}$'){throw'invalid_project_id'};$Id}
function Get-PCPath([string]$Id){Join-Path $script:PCProjects ((Get-PCSafeId $Id)+'.json')}
function Read-PCJson([string]$Path){Get-Content -Raw -Encoding UTF8 -LiteralPath $Path|ConvertFrom-Json}
function Write-PCJson($Value,[string]$Path){$tmp="$Path.tmp";$Value|ConvertTo-Json -Depth 20|Set-Content -Encoding UTF8 -LiteralPath $tmp;Move-Item -Force -LiteralPath $tmp -Destination $Path}
function Get-AI5Project([string]$Id){$p=Get-PCPath $Id;if(Test-Path $p){Read-PCJson $p}}
function Get-AI5Projects{$registry=Read-PCJson (Join-Path $script:PCRoot 'registry.json');@($registry.projects|ForEach-Object{Get-AI5Project $_}|Where-Object{$_})}
function Add-PCHistory($Project,[string]$Type,[string]$Actor,[string]$Detail){$Project.history+=,@{at=Get-PCNow;type=$Type;actor=$Actor;detail=$Detail}}
function Save-AI5Project($Project){$Project.timestamps.updatedAt=Get-PCNow;Write-PCJson $Project (Get-PCPath $Project.projectId)}
function Get-AI5ProjectSummary{
  $all=@(Get-AI5Projects);$count=@{};foreach($key in @('running','aiRunning','stopped','human','error','release','selling','completed','autoOn','autoOff')){$count[$key]=0}
  foreach($p in $all){if($p.status-eq'RUNNING'){$count.running++};if(@($p.aiState.psobject.Properties.Value)-contains'RUNNING'){$count.aiRunning++};if($p.status-in@('WAITING','BLOCKED','PAUSED')){$count.stopped++};if($p.blockedBy-eq'TEPPEI'){$count.human++};if($p.status-eq'FAILED'-or$p.stopCode-in@('ERROR_LOOP_STOP','CREDIT_PROTECTION_STOP')){$count.error++};if($p.phase-eq'RELEASE_READY'){$count.release++};if($p.phase-in@('PUBLISHED','OPERATING')){$count.selling++};if($p.status-eq'COMPLETED'){$count.completed++};if($p.autoExecution.mode-ne'OFF'){$count.autoOn++}else{$count.autoOff++}}
  @{projects=$all;counts=$count;scheduler=(Get-AI5SchedulerStatus);generatedAt=Get-PCNow;timezone='Asia/Tokyo'}
}
function New-AI5Project($Body){
  $id=Get-PCSafeId $Body.projectId;if(Test-Path (Get-PCPath $id)){throw'project_exists'};$now=Get-PCNow;$repoName=[string]$Body.repository
  $p=[ordered]@{schemaVersion=1;projectId=$id;name=[string]$Body.name;repository=[ordered]@{owner='';name=$repoName;defaultBranch='main';activeBranch='';latestCommit='';linkState=$(if($repoName){'LINKED'}else{'UNLINKED'});sync=@{state='UNKNOWN';localHead='';remoteHead='';defaultHead='';ahead=0;behind=0;dirty=$false;checkedAt='';error=''}};phase='IDEA';status='NOT_STARTED';blockedBy='NONE';stopCode='NONE';autoExecution=@{enabled=$false;mode='OFF'};executionPolicy=@{risk='LOW';costClass='NORMAL';maxRetry=2;dailyAutoRuns=3;requireApprovalAbove='HIGH';retryCount=0;runsToday=0;autoRunsToday=0;autoRunsDate='';failureFingerprint='';consecutiveFailures=0};execution=@{taskId='';lockId='';submittedAt='';resultRecoveredAt='';lastResult=''};timestamps=@{createdAt=$now;updatedAt=$now;stoppedAt='';resumedAt='';workStartedAt='';workCompletedAt='';lastGitHubSyncAt='';lastZeroActionAt='';lastCodexActionAt='';lastClaudeActionAt='';lastGeminiActionAt='';lastManusActionAt='';lastTeppeiActionAt='';publishedAt='';lastMaintenanceAt='';heartbeatAt=''};currentTask='';lastCompletedTask='';nextAction='';stopReason='';aiState=@{zero='IDLE';codex='IDLE';claude='NOT_REQUIRED';gemini='NOT_REQUIRED';manus='NOT_REQUIRED';notebooklm='NOT_REQUIRED'};qualityGate=@{tests='UNKNOWN';review='UNKNOWN';fieldValidation='UNKNOWN';release='UNKNOWN'};versions=@();history=@()}
  $p.execution|Add-Member recoveryRequired $false -Force;Add-PCHistory $p 'PROJECT_REGISTERED' 'TEPPEI' 'PROJECTS UIから登録';Save-AI5Project $p;$r=Read-PCJson (Join-Path $script:PCRoot 'registry.json');$r.projects+=,$id;$r.updatedAt=$now;Write-PCJson $r (Join-Path $script:PCRoot 'registry.json');$p
}
function Test-PCApproval([string]$Text){$Text-match'(?i)(課金|購入|契約|本番公開|販売開始|public repository|oauth|2fa|captcha|password|秘密|merge|force push|履歴破壊|大量削除|不可逆|法的同意)'}
function Set-AI5ProjectState($Project,$Body,[string]$Actor='ZERO'){
  $oldPhase=$Project.phase;$oldStatus=$Project.status;$now=Get-PCNow
  foreach($key in @('phase','status','blockedBy','stopCode','currentTask','lastCompletedTask','nextAction','stopReason')){if($null-ne$Body.$key){$Project.$key=$Body.$key}}
  if($Project.status-in@('WAITING','BLOCKED','FAILED','APPROVAL_REQUIRED','PAUSED')-and!$Project.timestamps.stoppedAt){$Project.timestamps.stoppedAt=$now}
  if($oldStatus-in@('WAITING','BLOCKED','FAILED','APPROVAL_REQUIRED','PAUSED')-and$Project.status-in@('READY','RUNNING','OPERATING')){$Project.timestamps.resumedAt=$now;$Project.timestamps.stoppedAt=''}
  if($Project.status-eq'RUNNING'-and$oldStatus-ne'RUNNING'){$Project.timestamps.workStartedAt=$now}
  if($Project.status-in@('COMPLETED','PUBLISHED','OPERATING')-and$oldStatus-eq'RUNNING'){$Project.timestamps.workCompletedAt=$now}
  if($Project.phase-eq'PUBLISHED'-and!$Project.timestamps.publishedAt){$Project.timestamps.publishedAt=$now;$Project.versions+=,@{publishedAt=$now;commit=$Project.repository.latestCommit}}
  if(Test-PCApproval (($Project.currentTask+' '+$Project.nextAction))){$Project.phase='WAITING_FOR_APPROVAL';$Project.status='APPROVAL_REQUIRED';$Project.blockedBy='TEPPEI';$Project.stopCode='TEPPEI_WAITING';$Project.timestamps.stoppedAt=$now}
  Add-PCHistory $Project 'STATE_CHANGED' $Actor "$oldPhase/$oldStatus → $($Project.phase)/$($Project.status)";Save-AI5Project $Project;$Project
}
function Set-AI5ProjectAuto($Project,[string]$Mode,[string]$Actor='TEPPEI'){if($Mode-notin@('OFF','DRY_RUN','LIVE')){throw'invalid_auto_mode'};$Project.autoExecution.mode=$Mode;$Project.autoExecution.enabled=($Mode-ne'OFF');Add-PCHistory $Project 'AUTO_MODE_CHANGED' $Actor $Mode;Save-AI5Project $Project;$Project}
function Test-AI5ProjectExecution($Project){
  Reset-AI5DailyRuns $Project
  if($Project.autoExecution.mode-eq'OFF'-or!$Project.autoExecution.enabled){return @{allowed=$false;reason='AUTO_OFF'}}
  if($Project.execution.recoveryRequired){return @{allowed=$false;reason='SYSTEM_RECOVERY_REQUIRED'}}
  if($Project.status-in@('RUNNING','PAUSED','APPROVAL_REQUIRED')){return @{allowed=$false;reason='STATUS_BLOCKED'}}
  if(!$Project.nextAction){return @{allowed=$false;reason='NEXT_STEP_MISSING'}}
  if($Project.repository.linkState-eq'LINKED'-and$Project.repository.sync.state-ne'SYNCED'){return @{allowed=$false;reason='GITHUB_SYNC_WAIT'}}
  if($Project.status-eq'APPROVAL_REQUIRED'-or$Project.blockedBy-eq'TEPPEI'-or(Test-PCApproval ($Project.currentTask+' '+$Project.nextAction))){return @{allowed=$false;reason='TEPPEI_APPROVAL_REQUIRED'}}
  if($Project.executionPolicy.costClass-in@('HIGH','VERY_HIGH')-or$Project.executionPolicy.risk-in@('HIGH','VERY_HIGH')){return @{allowed=$false;reason='CREDIT_PROTECTION_STOP'}}
  if($Project.executionPolicy.consecutiveFailures-ge2-or$Project.executionPolicy.retryCount-ge$Project.executionPolicy.maxRetry){return @{allowed=$false;reason='ERROR_LOOP_STOP'}}
  if($Project.executionPolicy.autoRunsToday-ge$Project.executionPolicy.dailyAutoRuns){return @{allowed=$false;reason='CREDIT_PROTECTION_STOP'}}
  @{allowed=$true;reason=$(if($Project.autoExecution.mode-eq'DRY_RUN'){'DRY_RUN_ELIGIBLE'}else{'READY'});mode=$Project.autoExecution.mode}
}
function Reset-AI5DailyRuns($Project){$date=[TimeZoneInfo]::ConvertTimeBySystemTimeZoneId([DateTimeOffset]::UtcNow,'Tokyo Standard Time').ToString('yyyy-MM-dd');if($Project.executionPolicy.autoRunsDate-ne$date){$Project.executionPolicy.autoRunsDate=$date;$Project.executionPolicy.autoRunsToday=0;$Project.executionPolicy.runsToday=0}}
function Write-PCLog($Project,[string]$Event,[string]$Reason,[string]$TaskId=''){$item=@{timestamp=Get-PCNow;projectId=$Project.projectId;event=$Event;status=$Project.status;reason=$Reason;taskId=$TaskId};Add-Content -Encoding UTF8 -LiteralPath (Join-Path $script:PCLogRoot ((Get-Date).ToString('yyyy-MM-dd')+'.jsonl')) -Value ($item|ConvertTo-Json -Compress);Add-PCHistory $Project $Event 'SYSTEM' $Reason}
function Update-AI5ProjectStopCode($Project){
  $states=@($Project.aiState.psobject.Properties.Value);$done=@($states|Where-Object{$_-notin@('DONE','PASSED','NOT_REQUIRED')}).Count-eq0
  $syncOk=$Project.repository.linkState-ne'LINKED'-or$Project.repository.sync.state-eq'SYNCED'
  if($done-and$syncOk-and$Project.nextAction-and$Project.status-notin@('RUNNING','PUBLISHED','OPERATING','ARCHIVED')){$Project.stopCode='ALL_AI_DONE_BUT_IDLE';$Project.status='WAITING';$Project.blockedBy='ZERO';if(!$Project.timestamps.stoppedAt){$Project.timestamps.stoppedAt=Get-PCNow};$Project.stopReason='必須AI工程とGitHub同期は完了したが、次工程が未投入'}
  elseif($Project.aiState.zero-ne'DONE'-and$Project.status-ne'RUNNING'){$Project.blockedBy='ZERO';$Project.stopCode='ZERO_STOPPED'}
  elseif($Project.aiState.zero-eq'DONE'-and$Project.aiState.codex-in@('READY','IDLE')-and$Project.nextAction-and$Project.status-ne'RUNNING'){$Project.blockedBy='CODEX';$Project.stopCode='CODEX_STOPPED'}
  elseif($Project.blockedBy-eq'ZERO'){$Project.stopCode='ZERO_STOPPED'}elseif($Project.blockedBy-eq'CODEX'){$Project.stopCode='CODEX_STOPPED'}elseif($Project.blockedBy-eq'CLAUDE'){$Project.stopCode='CLAUDE_STOPPED'}elseif($Project.blockedBy-eq'GEMINI'){$Project.stopCode='GEMINI_STOPPED'}elseif($Project.blockedBy-eq'MANUS'){$Project.stopCode='MANUS_STOPPED'}elseif($Project.blockedBy-eq'TEPPEI'){$Project.stopCode='TEPPEI_WAITING'}
  Save-AI5Project $Project;$Project
}
function Get-AI5ProjectRepoPath($Project){if($Project.repository.localPath){return[IO.Path]::GetFullPath($Project.repository.localPath)};$script:PCWorkspaceRoot}
function Get-AI5GitSnapshot($Project,[bool]$Fetch=$true){
  $root=Get-AI5ProjectRepoPath $Project;$branch=(& git -C $root branch --show-current 2>$null)-join'';if(!$branch){throw'local_repository_unavailable'}
  if($Fetch){& git -C $root fetch --quiet origin $branch 2>$null;if($LASTEXITCODE-ne0){throw'remote_fetch_failed'}}
  $local=(& git -C $root rev-parse HEAD 2>$null)-join'';$remote=(& git -C $root rev-parse "origin/$branch" 2>$null)-join'';$default=(& git -C $root rev-parse "origin/$($Project.repository.defaultBranch)" 2>$null)-join'';$dirty=@(& git -C $root status --porcelain 2>$null).Count-gt0
  if(!$remote){throw'remote_branch_unavailable'};$counts=((& git -C $root rev-list --left-right --count "$local...$remote" 2>$null)-join' ').Trim()-split'\s+';$ahead=[int]$counts[0];$behind=[int]$counts[1]
  $state=if($dirty){'DIRTY'}elseif($ahead-gt0-and$behind-gt0){'DIVERGED'}elseif($ahead-gt0){'LOCAL_AHEAD'}elseif($behind-gt0){'REMOTE_AHEAD'}else{'SYNCED'}
  @{state=$state;localHead=$local;remoteHead=$remote;defaultHead=$default;activeBranch=$branch;ahead=$ahead;behind=$behind;dirty=$dirty;checkedAt=Get-PCNow;error=''}
}
function Sync-AI5ProjectGit($Project,$Snapshot=$null,[bool]$Fetch=$true){
  if($Project.repository.linkState-ne'LINKED'){return $Project};try{$s=if($Snapshot){$Snapshot}else{Get-AI5GitSnapshot $Project $Fetch};foreach($key in @('state','localHead','remoteHead','defaultHead','ahead','behind','dirty','checkedAt','error')){$Project.repository.sync.$key=$s.$key};$Project.repository.activeBranch=$s.activeBranch;$Project.repository.latestCommit=$s.remoteHead;$Project.timestamps.lastGitHubSyncAt=$s.checkedAt;Write-PCLog $Project 'SYNC_CHECKED' $s.state;if($s.state-in@('REMOTE_AHEAD','DIVERGED','REMOTE_UNAVAILABLE')){$Project.blockedBy='GITHUB';$Project.stopCode='GITHUB_SYNC_WAIT';$Project.status='BLOCKED';$Project.stopReason="GitHub sync: $($s.state)";Write-PCLog $Project 'SYNC_BLOCKED' $Project.stopReason}elseif($Project.blockedBy-eq'GITHUB'){$Project.blockedBy='NONE';$Project.stopCode='NONE';$Project.stopReason=''}}catch{$Project.repository.sync.state='REMOTE_UNAVAILABLE';$Project.repository.sync.error=$_.Exception.Message;$Project.repository.sync.checkedAt=Get-PCNow;$Project.blockedBy='GITHUB';$Project.stopCode='GITHUB_SYNC_WAIT';$Project.status='BLOCKED';$Project.stopReason='GitHub remote unavailable';Write-PCLog $Project 'SYNC_BLOCKED' $_.Exception.Message};Save-AI5Project $Project;$Project
}
function Get-AI5SchedulerStatus{if(Test-Path $script:PCSchedulerPath){Read-PCJson $script:PCSchedulerPath}else{@{status='STOPPED';lastScan='';nextScan='';activeProject=''}}}
function Set-AI5SchedulerStatus($Value){Write-PCJson $Value $script:PCSchedulerPath}
function Get-AI5ActiveLocks{Get-ChildItem $script:PCLocks -Filter '*.lock' -ErrorAction SilentlyContinue|ForEach-Object{try{Read-PCJson $_.FullName}catch{}}}
function Get-AI5RepositoryCandidates([string]$Owner='daimon-app',$Candidates=$null){
  $registered=@(Get-AI5Projects|ForEach-Object{$_.repository.name}|Where-Object{$_});$names=if($Candidates){@($Candidates)}else{try{@(& gh repo list $Owner --limit 200 --json name,isArchived --jq '.[] | [.name,.isArchived] | @tsv' 2>$null)}catch{@()}}
  @($names|ForEach-Object{$parts=([string]$_)-split"`t";$name=$parts[0];if($name){@{owner=$Owner;name=$name;state=$(if($registered-contains$name){'REGISTERED'}elseif($parts[1]-eq'true'){'ARCHIVED'}else{'UNREGISTERED'})}}})
}
function New-AI5ProjectTask($Project){
  $id='PC-'+$Project.projectId+'-'+([DateTime]::UtcNow.ToString('yyyyMMddHHmmss'));$context=[ordered]@{projectId=$Project.projectId;repository=$Project.repository.name;branch=$Project.repository.activeBranch;currentTask=$Project.currentTask;nextAction=$Project.nextAction;phase=$Project.phase;risk=$Project.executionPolicy.risk;costClass=$Project.executionPolicy.costClass;retryCount=$Project.executionPolicy.retryCount;lockId=$id;requestedBy='PROJECT_CONTROL';autoExecution=$true}
  $instruction="PROJECT CONTROL task. Project: $($Project.projectId). Repository: $($Project.repository.name). Branch: $($Project.repository.activeBranch). Current task: $($Project.currentTask). Next action: $($Project.nextAction). Preserve unrelated work, run relevant tests, and report structured results."
  $body=[pscustomobject]@{taskId=('task_'+($id-replace'[^A-Za-z0-9_.-]','_'));message=$instruction;operation='code_change';source='PROJECT_CONTROL';priority='normal';conversationId='project-control';constraints=@('no main merge','no production publish')};$task=New-Task $body $id;$task|Add-Member projectContext $context;Save-AI5Task $task;$task
}
function Submit-AI5ProjectWork($Project,[bool]$DryRun=$false){
  $gate=Test-AI5ProjectExecution $Project;if(!$gate.allowed){Write-PCLog $Project 'QUEUE_SKIPPED' $gate.reason;Save-AI5Project $Project;return @{submitted=$false;reason=$gate.reason}}
  Write-PCLog $Project 'QUEUE_ELIGIBLE' $gate.reason;if($DryRun-or$Project.autoExecution.mode-eq'DRY_RUN'){Write-PCLog $Project 'QUEUE_SKIPPED' 'DRY_RUN';Save-AI5Project $Project;return @{submitted=$false;dryRun=$true;reason='DRY_RUN'}}
  $task=New-AI5ProjectTask $Project;$lock=Enter-AI5ProjectLock $Project.projectId 'CODEX' $task.taskId;$Project.status='RUNNING';$Project.blockedBy='NONE';$Project.stopCode='NONE';$Project.aiState.codex='QUEUED';$Project.timestamps.resumedAt=Get-PCNow;$Project.timestamps.workStartedAt='';$Project.execution.taskId=$task.taskId;$Project.execution.lockId=$lock.taskId;$Project.execution.submittedAt=Get-PCNow;$Project.executionPolicy.autoRunsToday++;$Project.executionPolicy.runsToday=$Project.executionPolicy.autoRunsToday;Write-PCLog $Project 'QUEUE_SUBMITTED' 'Bridge queue accepted' $task.taskId;Save-AI5Project $Project;Dispatch-Task $task;$Project.aiState.codex='RUNNING';$Project.timestamps.workStartedAt=Get-PCNow;Add-PCHistory $Project 'WORK_STARTED' 'CODEX' $task.taskId;Save-AI5Project $Project;@{submitted=$true;taskId=$task.taskId}
}
function Recover-AI5ProjectResult($Project){
  if($Project.execution.lastResult-eq'TIMEOUT'-and$Project.execution.resultRecoveredAt){return $Project}
  if(!$Project.execution.taskId){return $Project};$task=Get-AI5Task $Project.execution.taskId;if(!$task-or$task.status-in@('queued','planning','running','reviewing')){return $Project};$now=Get-PCNow;$resultStatus=([string]$task.result.status).ToUpperInvariant();$isTimeout=$task.errorType-eq'timeout'-or$resultStatus-eq'TIMEOUT';if($task.status-eq'completed'-and$resultStatus-in@('SUCCESS','COMPLETED')){$Project.aiState.codex='DONE';$Project.timestamps.workCompletedAt=$now;$Project.timestamps.lastCodexActionAt=$now;$Project.executionPolicy.retryCount=0;$Project.executionPolicy.consecutiveFailures=0;$Project.status='WAITING';$failedTests=@($task.result.tests|Where-Object{$_-match'(?i)fail|error|ng'});$Project.qualityGate.tests=$(if($failedTests.Count){'FAILED'}else{'PASSED'});Write-PCLog $Project 'WORK_COMPLETED' ($task.result.summary) $task.taskId}elseif($resultStatus-eq'PARTIAL'){$Project.aiState.codex='DONE';$Project.status='WAITING';$Project.stopReason=[string]$task.result.summary;$Project.nextAction=[string]$task.result.next_action;Write-PCLog $Project 'WORK_COMPLETED' 'PARTIAL' $task.taskId}else{$Project.aiState.codex='FAILED';$Project.status='BLOCKED';$Project.blockedBy=$(if($isTimeout){'SYSTEM'}else{'CODEX'});$Project.stopCode=$(if($isTimeout){'SYSTEM'}else{'CODEX_STOPPED'});$Project.timestamps.stoppedAt=$now;$Project.executionPolicy.retryCount++;$finger=[string]$task.result.failureReason;if($finger-and$finger-eq$Project.executionPolicy.failureFingerprint){$Project.executionPolicy.consecutiveFailures++}else{$Project.executionPolicy.failureFingerprint=$finger;$Project.executionPolicy.consecutiveFailures=1};Write-PCLog $Project $(if($isTimeout){'WORK_TIMEOUT'}else{'WORK_FAILED'}) $finger $task.taskId};$Project.execution.lastResult=$resultStatus;$Project.execution.resultRecoveredAt=$now;$Project.execution.recoveryRequired=$isTimeout;if(!$isTimeout){Exit-AI5ProjectLock $Project.projectId $Project.execution.lockId;$Project.execution.taskId='';$Project.execution.lockId=''};Save-AI5Project $Project;$Project
}
function Invoke-AI5ProjectScan([bool]$Fetch=$true,[bool]$DryRun=$false){$start=Get-PCNow;$state=@{status='RUNNING';lastScan=$start;nextScan=[DateTimeOffset]::Now.AddHours(1).ToString('o');activeProject='';lastResult='RUNNING';intervalMinutes=60};Set-AI5SchedulerStatus $state;$results=@();$dispatched=0;foreach($p in Get-AI5Projects){$p=Recover-AI5ProjectResult $p;$p=Sync-AI5ProjectGit $p $null $Fetch;$p=Update-AI5ProjectStopCode $p;$gate=Test-AI5ProjectExecution $p;$submission=$null;if($gate.allowed-and$dispatched-lt1){$submission=Submit-AI5ProjectWork $p $DryRun;if($submission.submitted){$dispatched++;$state.activeProject=$p.projectId}}else{if($gate.reason-in@('CREDIT_PROTECTION_STOP','ERROR_LOOP_STOP')){$p.status='BLOCKED';$p.blockedBy='CREDIT_LIMIT';$p.stopCode='CREDIT_PROTECTION_STOP';Write-PCLog $p 'CREDIT_STOP' $gate.reason}elseif($gate.reason-eq'TEPPEI_APPROVAL_REQUIRED'){$p.status='APPROVAL_REQUIRED';$p.blockedBy='TEPPEI';$p.stopCode='TEPPEI_WAITING';Write-PCLog $p 'APPROVAL_STOP' $gate.reason};Write-PCLog $p 'QUEUE_SKIPPED' $gate.reason;Save-AI5Project $p};$results+=,@{projectId=$p.projectId;execution=$gate;submission=$submission;stopCode=$p.stopCode}};$state.status='RUNNING';$state.lastResult='OK';Set-AI5SchedulerStatus $state;@{scannedAt=$start;projects=$results;dispatched=$dispatched;maxParallel=1}}
function Enter-AI5ProjectLock([string]$ProjectId,[string]$Owner,[string]$TaskId,[int]$Minutes=30){$path=Join-Path $script:PCLocks ((Get-PCSafeId $ProjectId)+'.lock');if(Test-Path $path){$old=Read-PCJson $path;if([DateTimeOffset]::Parse($old.expiresAt)-gt[DateTimeOffset]::Now){throw'project_locked'};$oldTask=if(Get-Command Get-AI5Task -ErrorAction SilentlyContinue){Get-AI5Task $old.taskId}else{$null};if($oldTask-and$oldTask.status-notin@('completed','failed','cancelled')){throw'project_lock_stale_task_unverified'};Remove-Item -Force $path};$value=@{projectId=$ProjectId;lockOwner=$Owner;lockedAt=Get-PCNow;expiresAt=[DateTimeOffset]::Now.AddMinutes($Minutes).ToString('o');taskId=$TaskId};Write-PCJson $value $path;$value}
function Exit-AI5ProjectLock([string]$ProjectId,[string]$TaskId){$path=Join-Path $script:PCLocks ((Get-PCSafeId $ProjectId)+'.lock');if(Test-Path $path){$lock=Read-PCJson $path;if($lock.taskId-eq$TaskId){Remove-Item -Force $path}}}
function Invoke-AI5ProjectRecovery([int]$Minutes=30){foreach($p in Get-AI5Projects){if($p.status-eq'RUNNING'-and$p.timestamps.heartbeatAt-and[DateTimeOffset]::Parse($p.timestamps.heartbeatAt)-lt[DateTimeOffset]::Now.AddMinutes(-$Minutes)){$p.status='BLOCKED';$p.blockedBy='SYSTEM';$p.stopCode='SYSTEM';$p.stopReason='heartbeat timeout; duplicate execution prevented';$p.timestamps.stoppedAt=Get-PCNow;Add-PCHistory $p 'STALE_RUNNING_RECOVERED' 'SYSTEM' $p.stopReason;Save-AI5Project $p}}}
