function Initialize-AI5ExternalTaskAdapter {param([string]$ServerRoot);$script:ExternalOutboxRoot=Join-Path $ServerRoot 'data\external-outbox';foreach($agent in @('manus','gemini')){New-Item -ItemType Directory -Force (Join-Path $script:ExternalOutboxRoot $agent)|Out-Null}}
function Submit-AI5ExternalTask {
  param($Task,[ValidateSet('manus','gemini')][string]$Agent)
  $bytes=New-Object byte[] 32;[Security.Cryptography.RandomNumberGenerator]::Fill($bytes);$returnToken=[Convert]::ToBase64String($bytes);$Task|Add-Member -NotePropertyName external_return_token_hash -NotePropertyValue (Get-AI5PayloadHash $returnToken) -Force;Save-AI5Task $Task
  $sourceSummary=if($Task.source_of_truth){[ordered]@{repository=$Task.source_of_truth.repository;branch=$Task.source_of_truth.branch;head=$Task.source_of_truth.head;snapshot_sha256=$Task.source_of_truth.snapshot_sha256;commit_url=$Task.source_of_truth.commit_url;documents=@($Task.source_of_truth.documents.PSObject.Properties|ForEach-Object{[ordered]@{name=$_.Name;exists=$_.Value.exists;path=$_.Value.path;sha=$_.Value.sha;content_sha256=$_.Value.content_sha256}});inventory=@($Task.source_of_truth.inventory|Select-Object -First 500)}}else{$null}
  $request=Protect-AI5Object ([ordered]@{task_id=$Task.task_id;project_id=$Task.project_id;product_id=$Task.product_id;objective=$Task.objective;assigned_ai=$Agent;support_ai=@($Task.support_ai);writer=$Task.writer;priority=$Task.priority;source_commit=$Task.source_commit;source_of_truth=$sourceSummary;expected_output=$Task.expected_output;acceptance_criteria=@($Task.acceptance_criteria);constraints=@($Task.constraints);result_contract=[ordered]@{acceptance_outcomes='one exact criterion PASS with verified https/path/commit evidence per acceptance criterion';tests='each entry must use NAME PASS N/N with N > 0';qa='each entry must use NAME PASS N/N with N > 0';evidence='reachable https URL, existing repository path:, or source-bound commit:'};return_route="POST /api/tasks/$($Task.task_id)/result";created_at=[DateTime]::UtcNow.ToString('o')});$request.return_token=$returnToken
  $path=Join-Path (Join-Path $script:ExternalOutboxRoot $Agent) ($Task.task_id+'.json');$temp=$path+'.tmp';$request|ConvertTo-Json -Depth 12|Set-Content -LiteralPath $temp -Encoding UTF8;Move-Item -LiteralPath $temp -Destination $path -Force;$request
}
function Test-AI5ExternalReturnToken {param($Task,[string]$Token);if(!$Task.external_return_token_hash-or![string]$Token){return $false};$actual=Get-AI5PayloadHash $Token;$a=[Text.Encoding]::ASCII.GetBytes([string]$Task.external_return_token_hash);$b=[Text.Encoding]::ASCII.GetBytes($actual);$a.Length-eq$b.Length-and[Security.Cryptography.CryptographicOperations]::FixedTimeEquals($a,$b)}
function Get-AI5ExternalOutbox {param([ValidateSet('manus','gemini')][string]$Agent);@(Get-ChildItem (Join-Path $script:ExternalOutboxRoot $Agent)-Filter'*.json'-ErrorAction SilentlyContinue|Sort-Object LastWriteTime|ForEach-Object{Get-Content -Raw -Encoding UTF8 $_.FullName|ConvertFrom-Json})}
function Complete-AI5ExternalTask {param([string]$TaskId,[string]$Agent);$path=Join-Path (Join-Path $script:ExternalOutboxRoot $Agent) ($TaskId+'.json');if(Test-Path $path){Remove-Item -LiteralPath $path -Force}}
