$ErrorActionPreference='Stop';$server=Split-Path $PSScriptRoot;. ([ScriptBlock]::Create((Get-Content -Raw -Encoding UTF8 (Join-Path $server 'github-bus\GitHubResultLoop.ps1'))));$root=Join-Path ([IO.Path]::GetTempPath()) ('ai5-gh-loop-'+[guid]::NewGuid().ToString('N'))
function Assert-GH($ok,$message){if(!$ok){throw$message}}
try{Initialize-AI5GitHubResultLoop $root;$mode=Set-AI5GitHubBusMode 'GITHUB_DEGRADED' 'DEGRADED';Assert-GH ($mode.mode-eq'GITHUB_DEGRADED') 'degraded mode failed'
  $task=New-AI5GitHubBusTask ([pscustomobject]@{task_id='task-manus-1';project_id='p02';product_id='p02';assigned_ai='manus';writer='manus';objective='LP QA';instructions='read only browser QA';acceptance_criteria=@('QA PASS');source_repository='daimon-app/ittebako';source_branch='feature';source_commit='abc';max_retry=3});Assert-GH ($task.status-eq'QUEUED') 'task create failed'
  Assert-GH (@(Get-AI5GitHubBusTasks 'manus').Count-eq1) 'AI queue failed';$lock=Claim-AI5GitHubBusTask $task.task_id 'manus' 1;Assert-GH ($lock.writer-eq'manus') 'claim/lock failed';$blocked=$false;try{Claim-AI5GitHubBusTask $task.task_id 'manus' 1|Out-Null}catch{$blocked=$true};Assert-GH $blocked 'single writer failed';$heartbeat=Update-AI5GitHubBusHeartbeat $task.task_id 'manus';Assert-GH $heartbeat.heartbeat_at 'heartbeat failed'
  $saved=New-AI5GitHubBusResult ([pscustomobject]@{task_id=$task.task_id;result_version=1;ai='manus';result='PASS';summary='LP QA PASS';evidence=@('screenshot');tests=@('qa PASS');recommended_next_action='Claude audit'});Assert-GH (!$saved.duplicate) 'result save failed';$duplicate=New-AI5GitHubBusResult ([pscustomobject]@{task_id=$task.task_id;result_version=1;ai='manus';result='PASS';summary='duplicate'});Assert-GH $duplicate.duplicate 'result idempotency failed';$collected=Invoke-AI5GitHubResultCollector;Assert-GH ($collected.processed-eq1-and@(Get-AI5ZeroInbox).Count-eq1) 'collector/inbox failed';$nextAudit=Get-AI5GitHubBusTasks|Where-Object{$_.parent_task_id-eq$task.task_id};Assert-GH ($nextAudit.assigned_ai-eq'claude') 'PASS next-stage redispatch failed';Assert-GH ((Invoke-AI5GitHubResultCollector).processed-eq0) 'collector duplicate processing failed'
  $fail=New-AI5GitHubBusTask ([pscustomobject]@{task_id='task-fail';project_id='p';assigned_ai='codex';writer='codex';objective='fix';instructions='fix';max_retry=2});Claim-AI5GitHubBusTask $fail.task_id 'codex'|Out-Null;New-AI5GitHubBusResult ([pscustomobject]@{task_id=$fail.task_id;ai='codex';result='FAIL';summary='failed'})|Out-Null;$cycle=Invoke-AI5GitHubResultCollector;Assert-GH ($cycle.redispatched-eq1-and(Get-AI5GitHubBusTasks|Where-Object{$_.task_id-eq'task-fail-retry-1'})) 'FAIL retry redispatch failed'
  $limit=New-AI5GitHubBusTask ([pscustomobject]@{task_id='task-limit';project_id='p';assigned_ai='codex';writer='codex';objective='limit';instructions='limit';retry_count=2;max_retry=2});Claim-AI5GitHubBusTask $limit.task_id 'codex'|Out-Null;New-AI5GitHubBusResult ([pscustomobject]@{task_id=$limit.task_id;ai='codex';result='FAIL';summary='limit reached'})|Out-Null;Invoke-AI5GitHubResultCollector|Out-Null;$limitInbox=Get-AI5ZeroInbox|Where-Object{$_.task_id-eq'task-limit'};Assert-GH ($limitInbox.decision-eq'ESCALATED'-and!(Get-AI5GitHubBusTasks|Where-Object{$_.parent_task_id-eq'task-limit'})) 'retry limit failed'
  $browser=New-AI5GitHubBusTask ([pscustomobject]@{task_id='task-browser';project_id='p';assigned_ai='codex';writer='codex';objective='browser check';instructions='browser';max_retry=3});Claim-AI5GitHubBusTask $browser.task_id 'codex'|Out-Null;New-AI5GitHubBusResult ([pscustomobject]@{task_id=$browser.task_id;ai='codex';result='BLOCKED';summary='browser degraded';blockers=@('BLOCKED_BROWSER')})|Out-Null;Invoke-AI5GitHubResultCollector|Out-Null;$fallback=Get-AI5GitHubBusTasks|Where-Object{$_.parent_task_id-eq'task-browser'};Assert-GH ($fallback.assigned_ai-eq'manus') 'browser fallback failed'
  $approval=New-AI5GitHubBusTask ([pscustomobject]@{task_id='task-approval';project_id='p';assigned_ai='manus';writer='manus';objective='publish';instructions='prepare only';approval_required=$true});New-AI5GitHubBusResult ([pscustomobject]@{task_id=$approval.task_id;ai='manus';result='PASS';summary='ready';approval_required=$true})|Out-Null;Invoke-AI5GitHubResultCollector|Out-Null;$approvalInbox=Get-AI5ZeroInbox|Where-Object{$_.task_id-eq'task-approval'};Assert-GH ($approvalInbox.decision-eq'APPROVAL_REQUIRED'-and!(Get-AI5GitHubBusTasks|Where-Object{$_.parent_task_id-eq'task-approval'})) 'approval gate failed'
  $secretBlocked=$false;try{New-AI5GitHubBusTask ([pscustomobject]@{task_id='task-secret';assigned_ai='codex';objective='x';instructions='api_key=secretvalue'})|Out-Null}catch{$secretBlocked=$true};Assert-GH $secretBlocked 'secret protection failed'
  $stale=New-AI5GitHubBusTask ([pscustomobject]@{task_id='task-stale';project_id='p';assigned_ai='codex';writer='codex';objective='stale';instructions='stale'});$null=Claim-AI5GitHubBusTask $stale.task_id 'codex' 1;$staleTaskPath=Join-Path $script:GHTasks 'task-stale.json';$staleTask=Read-GHBusJson $staleTaskPath;$staleTask.status='QUEUED';Write-GHBusJson $staleTask $staleTaskPath;$staleLockPath=Join-Path $script:GHLocks 'task-stale.json';$staleLock=Read-GHBusJson $staleLockPath;$staleLock.expires_at=[DateTimeOffset]::Now.AddMinutes(-1).ToString('o');Write-GHBusJson $staleLock $staleLockPath;$reclaimed=Claim-AI5GitHubBusTask $stale.task_id 'codex';Assert-GH ($reclaimed.owner-eq'codex') 'same-owner stale lock recovery failed'
  $beforeReload=@(Get-AI5GitHubBusTasks).Count;Initialize-AI5GitHubResultLoop $root;Assert-GH (@(Get-AI5GitHubBusTasks).Count-eq$beforeReload) 'GitHub bus reload persistence failed';$status=Get-AI5GitHubBusStatus;Assert-GH ($status.inbox-ge5-and$status.remoteEnabled-eq$false) 'status/persistence failed';'GITHUB_RESULT_LOOP_TESTS_OK'
}finally{if(Test-Path $root){Remove-Item -LiteralPath $root -Recurse -Force}}
