$ErrorActionPreference='Stop';$server=Split-Path $PSScriptRoot;. ([ScriptBlock]::Create((Get-Content -Raw -Encoding UTF8 (Join-Path $server 'storage\LongMessageIngestion.ps1'))));. ([ScriptBlock]::Create((Get-Content -Raw -Encoding UTF8 (Join-Path $server 'security\Security.ps1'))))
$root=Join-Path ([IO.Path]::GetTempPath()) ('ai5-long-'+[guid]::NewGuid().ToString('N'));try{
Initialize-AI5LongMessages $root;$message=('long instruction '+('x'*7000));$chunks=@($message.Substring(0,4000),$message.Substring(4000));$hash=Get-AI5TextHash $message;$id='draft0123456789abcdef'
$draft=New-AI5LongMessageDraft ([pscustomobject]@{messageId=$id;totalChunks=2;totalLength=$message.Length;contentHash=$hash});if($draft.receivedCount-ne0){throw'draft not empty'}
$null=Save-AI5LongMessageChunk $id 0 ([pscustomobject]@{content=$chunks[0];chunkHash=(Get-AI5TextHash $chunks[0])});$duplicate=Save-AI5LongMessageChunk $id 0 ([pscustomobject]@{content=$chunks[0];chunkHash=(Get-AI5TextHash $chunks[0])});if($duplicate.receivedCount-ne1){throw'duplicate was not idempotent'}
try{$null=Save-AI5LongMessageChunk $id 0 ([pscustomobject]@{content='different';chunkHash=(Get-AI5TextHash 'different')});throw'conflicting duplicate accepted'}catch{if($_.Exception.Message-ne'duplicate_chunk_conflict'){throw}}
try{$null=Complete-AI5LongMessage $id;throw'missing chunk accepted'}catch{if($_.Exception.Message-ne'missing_chunk'){throw}}
try{$null=Save-AI5LongMessageChunk $id 1 ([pscustomobject]@{content=$chunks[1];chunkHash=('0'*64)});throw'bad chunk hash accepted'}catch{if($_.Exception.Message-ne'chunk_hash_mismatch'){throw}}
$null=Save-AI5LongMessageChunk $id 1 ([pscustomobject]@{content=$chunks[1];chunkHash=(Get-AI5TextHash $chunks[1])});$complete=Complete-AI5LongMessage $id;if($complete.message-ne$message){throw'reconstruction mismatch'};Set-AI5LongMessageCompleted $complete 'AI5-test-0001';if((Complete-AI5LongMessage $id).taskId-ne'AI5-test-0001'){throw'completed idempotency failed'}
foreach($bad in @([pscustomobject]@{messageId='../escape-invalid';totalChunks=1;totalLength=1;contentHash=('0'*64)},[pscustomobject]@{messageId='valid0123456789abcdef';totalChunks=65;totalLength=1;contentHash=('0'*64)},[pscustomobject]@{messageId='valid1123456789abcdef';totalChunks=1;totalLength=262145;contentHash=('0'*64)})){try{$null=New-AI5LongMessageDraft $bad;throw'bad draft accepted'}catch{if($_.Exception.Message-eq'bad draft accepted'){throw}}}
if((Test-AI5Instruction ('x'*4001))-ne'long_message_ingestion_required'){throw'direct long input not redirected'};if(Test-AI5Instruction ('x'*4001) -Long){throw'valid long input rejected'};if((Test-AI5Instruction ('x'*262145) -Long)-ne'message_too_large'){throw'oversized long input accepted'}
'LONG_MESSAGE_INGESTION_TESTS_OK'}finally{if(Test-Path $root){Remove-Item -LiteralPath $root -Recurse -Force}}
